### ISSUE TITLE
[Question]: 能在deepstream中使用吗？也没有看到int8的转换文档

### ISSUE THREAD

**Issue by tms2003** [laugh12321/TensorRT-YOLO#10]
同上

**Comment by laugh12321** [comment]
没有尝试过在DeepStream中使用，理论上应该是可以的，欢迎尝试。目前只在PC和Jetson上进行过裸跑测试。
TensorRT 的PTQ int8量化的详细文档后续会给出。以下时简要教程

## PTQ int8 量化的简要教程

1. 在 `calibration.yaml` 中进行配置。
> 当 `dynamic = True` 时，需要对`shapes`进行配置，且`batch_shape == shapes.opt`。
> `calibrator.data` 为校准数据文件夹。

2. 执行 `python ptq_calibration.py`
