### ISSUE TITLE
[CUDA ERROR]: Too many resources requested for launch

### ISSUE THREAD

**Issue by liautumn** [laugh12321/TensorRT-YOLO#11]
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/93562667/c470b468-69d6-4f4a-be31-894358141253)
代码也没动，运行就报这个问题

**Comment by laugh12321** [comment]
你看看你用的显卡最大支持每个块有多少个线程，代码里是32*32个，你改成16*16试一下。

```cpp
// dim3 blockSize(32, 32);
dim3 blockSize(16, 16);
```

**Comment by liautumn** [comment]
ok, 感谢
