### ISSUE TITLE
trtexec export tensorrt model failed

### ISSUE THREAD

**Issue by fungtion** [laugh12321/TensorRT-YOLO#13]
when running `trtexec --onnx=model.onnx --saveEngine=model.engine --fp16`, it failed to create engine because could not find any implementation for node /model/model/model.0/conv/Conv

![image](https://github.com/laugh12321/TensorRT-YOLO/assets/10267392/9338fd51-c550-468f-bc3a-ebf2d190b19e)

**Comment by laugh12321** [comment]
Is `model.onnx` exported using `export.py`? What is the version of TensorRT you're using? Could you provide the model and its version for testing purposes?

**Comment by fungtion** [comment]
Sorry for late. I'm using TensorRT 8.6.1.6 + cuda 11.8 + cudnn 8.8 to export yolov9-c-converted.onnx to TensorRT model. I test this configuration on 4090 and P4, and it works fine, but when I used the same configuration on Titan x, it reported this error.

**Comment by laugh12321** [comment]
If you're encountering export failures specifically on certain devices, it could be an issue related to TensorRT. You may want to refer to https://github.com/NVIDIA/TensorRT/issues/3640 for more information and potential solutions.

**Comment by fungtion** [comment]
Thanks, I will check that
