### ISSUE TITLE
[Help]: 请问如何实现tensorrt模型对多视频流输入的同时预测呢？

### ISSUE THREAD

**Issue by Zzzames** [laugh12321/TensorRT-YOLO#17]
我对yolov5-master中的detect.py做了修改，可以实现开多线程读取多视频流。然后调用pytorch的模型进行同时推理，但是换成.engine模型就不行了，想问问作者这块问题怎么解？

**Comment by laugh12321** [comment]
[ultralytics/yolov5](https://github.com/ultralytics/yolov5) 是支持TensorRT后端推理的，所以你改成多线程理论上也是可以正常运行的。

[laugh12321/TensorRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO) 也是支持实现C++/Python进行多线程推理多个模型的，只需要起多个`TRTYOLO`/ `Detection` 即可，目前还没有在仓库中给出多线程推理的例子，可自行实现。
