### ISSUE TITLE
[Question]: Why are the methods different when loading models?

### ISSUE THREAD

**Issue by Tom-Teamo** [laugh12321/TensorRT-YOLO#20]
Hi, I am a new guy in object detection.

I looked into source code and found that when loading YOLOv8, it uses `return YOLO(model=weights, verbose=False).model` which is a self-implemented method. However in YOLOv5 and v9, it uses the  `torch.hub.load`. So I wanna know what causes this difference？

**Comment by laugh12321** [comment]
由于大多数人使用的是官方仓库来训练[YOLOv5](https://github.com/ultralytics/yolov5)、[YOLOv7](https://github.com/WongKinYiu/yolov7)和[YOLOv9](https://github.com/WongKinYiu/yolov9)模型，而不是通过`ultralytics.YOLO`进行训练。

当直接使用`torch.load`加载模型，且脚本不在项目目录下时，会出现`ModuleNotFoundError: No module named 'models'`的错误。这是YOLOv5的一个历史遗留问题。由于YOLOv7和YOLOv9是在YOLOv5的基础上进行修改的，因此它们也存在这个问题。ultralytics社区建议使用`torch.hub.load`来加载模型。

> https://github.com/ultralytics/yolov5/issues/10121

**Comment by Tom-Teamo** [comment]
好的，感谢解答，请问为什么YOLOv5不使用`torch.hub.load`？

**Comment by laugh12321** [comment]
`ultralytics`没有提供`hubconf.py`

**Comment by Tom-Teamo** [comment]
ok 👍
