### ISSUE TITLE
[Question]: 关于【使用了 CUDA 核函数来加速前处理过程】在哪里体现

### ISSUE THREAD

**Issue by songsong695** [laugh12321/TensorRT-YOLO#23]
您好，请问”使用了 CUDA 核函数来加速前处理过程“，体现在哪里呢，是在ImageBatcher类里面吗，没有发现加速的部分呢，谢谢！

**Comment by laugh12321** [comment]
【CUDA核函数加速前处理】在[老版本的Python代码](https://github.com/laugh12321/TensorRT-YOLO/blob/v1.0/python/infer/yolo.py#L67)中有使用，因为在Python上无法实现真正的多stream并行，就改为给[C++](https://github.com/laugh12321/TensorRT-YOLO/blob/2cd01467669c47ea6539acc971ba8e7e24bde88b/source/deploy/vision/detection.cpp#L172)用了。你要是需要后面可以加上。

**Comment by songsong695** [comment]
> 【CUDA核函数加速前处理】在[老版本的Python代码](https://github.com/laugh12321/TensorRT-YOLO/blob/v1.0/python/infer/yolo.py#L67)中有使用，因为在Python上无法实现真正的多stream并行（batch是一不影响），就改为给[C++](https://github.com/laugh12321/TensorRT-YOLO/blob/2cd01467669c47ea6539acc971ba8e7e24bde88b/source/deploy/vision/detection.cpp#L172)用了。你要是需要后面可以加上。

好的，谢谢您！
