### ISSUE TITLE
[Help]: 无法导出onnx模型

### ISSUE THREAD

**Issue by liautumn** [laugh12321/TensorRT-YOLO#24]
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/93562667/d28a01be-9488-4237-b2be-26eb358dd742)
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/93562667/4c7d8f6c-db21-4d30-8b71-d667a2682973)

![image](https://github.com/laugh12321/TensorRT-YOLO/assets/93562667/5769188c-b17b-4d12-b934-bf25e7bc0249)

**Comment by liautumn** [comment]
执行完是空的，没生成onnx

**Comment by laugh12321** [comment]
你下载模型了吗？

**Comment by liautumn** [comment]
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/93562667/ea127c72-c07e-4d55-b538-bb9fbd8e35b3)

**Comment by laugh12321** [comment]
指令运行结果图看一下，上面没发完

**Comment by liautumn** [comment]
> 指令运行结果图看一下，上面没发完

![image](https://github.com/laugh12321/TensorRT-YOLO/assets/93562667/d935f706-e2c3-4a19-95d7-3f195b95171d)

**Comment by laugh12321** [comment]
同步一下仓库代码，或者更新一下`tensorrt-yolo`包

```
pip install tensorrt-yolo==3.0.2
```
实际效果应该时这样的：
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/38065710/c130f5b5-7d9f-42e0-bf3c-c749512cf156)

**Comment by liautumn** [comment]
> 同步一下仓库代码，或者更新一下`tensorrt-yolo`包
> 
> ```
> pip install tensorrt-yolo==3.0.2
> ```
> 
> 实际效果应该是这样的： ![图像](https://private-user-images.githubusercontent.com/38065710/328790969-c130f5b5-7d9f-42e0-bf3c-c749512cf156.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTI3MTYsIm5iZiI6MTcxNTE1MjQxNiwicGF0aCI6Ii8zODA2NTcxMC8zMjg3OTA5NjktYzEzMGY1YjUtN2Q5Zi00MmUwLWJmM2MtYzc0OTUxMmNmMTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA3MTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYzFkZTNjMTE0ZWM4NDA2ZDZmMWE0ZDZkMGI3YWQxOGRkNzE0OGNiMTZkNzkzNmY0NDc0ODkwODI3YzgyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gfwESHNXkl89R7dtfWQwO84SZyVcwsukO6AskM_YHr8)

好的，我试试

**Comment by laugh12321** [comment]
@liautumn 可以导出的话这个issue就关闭了。

**Comment by liautumn** [comment]
> @liautumn 可以导出的话这个issue就关闭了。

可以了，非常感谢

**Comment by sanersbug** [comment]
@laugh12321 为啥我更新到最新的tensorrt-yolo版本还是不行，结果还是空的，请问你是调整了什么才能正常导出的

**Comment by laugh12321** [comment]
@sanersbug 
- 你导出的是哪个型号的模型？
- 是在官方仓库训练和下载的吗？
- 是Windows还是Linux？
- 导出日志是什么样的？
- 有没有尝试创建新环境后直接`pip install tensorrt_yolo`

**Comment by sanersbug** [comment]
@laugh12321 是我自己训练的yolov8s，用的就是官网的项目训练的，在Windows上操作的，我是运行ptq_calibration.py脚本，缺啥装啥，没有在创建新环境后直接pip install tensorrt_yolo
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/31174846/c1e6e19d-7da2-430a-a8b6-ba16857cf5fd)

**Comment by laugh12321** [comment]
@sanersbug 我遇到过这个问题，创建一个新环境直接pip install tensorrt_yolo就好了。
