### ISSUE TITLE
[Help]: TypeError: 'tuple' object does not support item assignment

### ISSUE THREAD

**Issue by sanersbug** [laugh12321/TensorRT-YOLO#25]
命令行：python .\detect.py -e D:\Project\TensorRT-YOLO-main\yolov8s.engine -i D:\Project\yolov8\data\tests
错误如下：
[I] Loading bytes from D:\Project\TensorRT-YOLO-main\yolov8s.engine
[E] 2: [pluginV2DynamicExtRunner.cpp::nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute::115] Error Code 2: Internal Error (Assertion pluginUtils::isSuccess(status) failed. )
[E] 2: [pluginV2DynamicExtRunner.cpp::nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute::115] Error Code 2: Internal Error (Assertion pluginUtils::isSuccess(status) failed. )
[E] 2: [pluginV2DynamicExtRunner.cpp::nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute::115] Error Code 2: Internal Error (Assertion pluginUtils::isSuccess(status) failed. )
[E] 2: [pluginV2DynamicExtRunner.cpp::nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute::115] Error Code 2: Internal Error (Assertion pluginUtils::isSuccess(status) failed. )
[E] 2: [pluginV2DynamicExtRunner.cpp::nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute::115] Error Code 2: Internal Error (Assertion pluginUtils::isSuccess(status) failed. )
[E] 2: [pluginV2DynamicExtRunner.cpp::nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute::115] Error Code 2: Internal Error (Assertion pluginUtils::isSuccess(status) failed. )
[E] 2: [pluginV2DynamicExtRunner.cpp::nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute::115] Error Code 2: Internal Error (Assertion pluginUtils::isSuccess(status) failed. )
[E] 2: [pluginV2DynamicExtRunner.cpp::nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute::115] Error Code 2: Internal Error (Assertion pluginUtils::isSuccess(status) failed. )
[E] 2: [pluginV2DynamicExtRunner.cpp::nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute::115] Error Code 2: Internal Error (Assertion pluginUtils::isSuccess(status) failed. )
[E] 2: [pluginV2DynamicExtRunner.cpp::nvinfer1::rt::cuda::PluginV2DynamicExtRunner::execute::115] Error Code 2: Internal Error (Assertion pluginUtils::isSuccess(status) failed. )
[I] warmup 10 iters cost 231.77 ms.
[I] Infering data in D:\Project\yolov8\data\tests
Processing batches ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "D:\Project\TensorRT-YOLO-main\demo\detect\detect.py", line 80, in <module>
    main()
  File "D:\SoftWare\Anaconda3\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\T800\AppData\Roaming\Python\Python311\site-packages\rich_click\rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\SoftWare\Anaconda3\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SoftWare\Anaconda3\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\TensorRT-YOLO-main\demo\detect\detect.py", line 56, in main
    detections = model.infer(batch, batch_shape)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\T800\AppData\Roaming\Python\Python311\site-packages\tensorrt_yolo\infer\yolo.py", line 243, in infer
    tensor.shape[0] = batch_size
    ~~~~~~~~~~~~^^^
TypeError: 'tuple' object does not support item assignment

**Comment by laugh12321** [comment]
**To address the issue you're experiencing, please follow these steps:**

1. **Verify the Version of `tensorrt-yolo`:** First, check the current version of the `tensorrt-yolo` package installed in your environment. You can do this by running the following command:

   ```bash
   pip show tensorrt-yolo
   ```

2. **Update if Necessary:** If the version displayed is not `3.0.2`, you will need to update the package to this specific version. You can update the package using the following pip command:

   ```bash
   pip install tensorrt-yolo==3.0.2
   ```

   This command will ensure that you have the correct version that may be required for your application to function as expected.

3. **Retest Your Application:** After updating the package, rerun your application to see if the issue has been resolved.

If you continue to encounter problems after updating the package, please provide additional details regarding the issue, and I'll be glad to assist you further.

**Comment by laugh12321** [comment]
@sanersbug Hello, just checking in—has the issue been resolved? If so, I'll close it.

**Comment by sanersbug** [comment]
> @sanersbug Hello, just checking in—has the issue been resolved? If so, I'll close it.

I checked my env, the tensorrt-yolo==3.0.2,  the question i met is still exists.

**Comment by sanersbug** [comment]
@laugh12321 I checked my env, the tensorrt-yolo==3.0.2, the question i met is still exists.

**Comment by sanersbug** [comment]
@laugh12321 The key of this question is in tensorrt_yolo\infer\yolo.py", line 243

tensorrt_yolo\infer\yolo.py", line 243, in infer
tensor.shape[0] = batch_size
~~~~~~~~~~~~^^^
TypeError: 'tuple' object does not support item assignment

**Comment by laugh12321** [comment]
@sanersbug "Please apply the changes from the commit at https://github.com/laugh12321/TensorRT-YOLO/commit/24ea950b31f6c73ff9bd853034310da45d45c02b and provide the updated allocate_buffers function code."

**Comment by sanersbug** [comment]
@laugh12321  I checked my yolo.py that installed in tensorrt-yolo==3.0.2 , the line of 70 ,is :  batch, _, *imgsz = shape, it is nothing wrong with what is written here
Do I need to reinstall tensorrt-yolo？

**Comment by laugh12321** [comment]
@sanersbug Please update the repository code and check if the usage of ImageBatcher in your `detect.py` is consistent with [this link](https://github.com/laugh12321/TensorRT-YOLO/blob/main/demo/detect/detect.py#L54).

**Comment by sanersbug** [comment]
this is the detect.py in my computer:
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/31174846/39410167-8d03-4a80-b9d2-7a3d1a23fc2f)
it is the same with [this link](https://github.com/laugh12321/TensorRT-YOLO/blob/main/demo/detect/detect.py#L54).

**Comment by sanersbug** [comment]
@laugh12321  I download the code again，the error is still exists. my tensorRT is tensorrt==10.0.0b6, is this influence it ?

**Comment by laugh12321** [comment]
@sanersbug Print `type(batch)` to view the type of batch, which should be np.ndarray instead of `tuple`.

**Comment by sanersbug** [comment]
@laugh12321 
it is like :
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/31174846/a4014207-d158-4ddb-8a88-bcf22a97d05b)

**Comment by laugh12321** [comment]
@sanersbug Is using `trtyolo infer` normal.

**Comment by sanersbug** [comment]
@laugh12321 I use trtexec to re export the engine, it is work.The main reason of the error is that i use export.py in yolov8 project generate the engine. it doesn't match your code ?

**Comment by laugh12321** [comment]
@sanersbug Please take a screenshot of the exported onnx output. This project is a YOLO model with NMS inference

**Comment by laugh12321** [comment]
正如之前的回答所说，这个项目旨在导出带有 EfficientNMS 插件的 YOLO 模型，然后进行推理。你不能直接使用原始模型(不带插件的)进行推理。请参考 https://github.com/laugh12321/TensorRT-YOLO/blob/main/docs/cn/model_export.md 中的说明，导出带 EfficientNMS 插件的模型，然后再进行推理。

> Like 
> ![image](https://private-user-images.githubusercontent.com/38065710/329214053-19a8cc2a-ed77-4124-8a8c-2315bb9fab21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzODQzODEsIm5iZiI6MTcxNTM4NDA4MSwicGF0aCI6Ii8zODA2NTcxMC8zMjkyMTQwNTMtMTlhOGNjMmEtZWQ3Ny00MTI0LThhOGMtMjMxNWJiOWZhYjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDIzMzQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NzRmMDMyYjFhYzk5MzBmMDcyODczY2E0YzVmMjg4NmJkZWEyMzA2NmNkM2JhNDE4Yjc3ODk4OGQ1ODBjYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2yt9tJoY8dIzi6eVrTdBSoyAkOBpSUWkfDDSRM-vKmE)
