### ISSUE TITLE
[Help]: how to export yolov10 to onnx?

### ISSUE THREAD

**Issue by zhongqiu1245** [laugh12321/TensorRT-YOLO#28]
cmd
```
trtyolo export -w yolov10m.pt -v yolov10 -o models
```

however:
```
[I] Starting export with Pytorch.
[E] YOLO version 'yolov10' not supported
```
Could you tell me what is the right cmd to export yolov10 to onnx? Thx!

**Comment by laugh12321** [comment]
@zhongqiu1245 The export method is detailed in commit [62071cb](https://github.com/laugh12321/TensorRT-YOLO/commit/62071cb0993b87220243b8f9aaa35fe98b6917d1). Here's a step-by-step explanation:

1. Download the fork [laugh12321/yolov10/tree/nms](https://github.com/laugh12321/yolov10/tree/nms) to your local machine and set up the environment as per the instructions.
2. Refer to the [THU-MIG/yolov10#29-2316587365](https://github.com/THU-MIG/yolov10/pull/29#issue-2316587365) method for export.

> YOLOv10 is NMS-free, and adding TRT EfficientNMS here is to facilitate project usage. Practical tests show that the processing speed with EfficientNMS is similar to v10postprocess. For specific benchmarks, please refer to [THU-MIG/yolov10#29-2131005872](https://github.com/THU-MIG/yolov10/pull/29#issuecomment-2131005872).

**Comment by zhongqiu1245** [comment]
Thank you!
