### ISSUE TITLE
[Help]: host_config.h: fatal error C1189: #error: – unsupported Microsoft Visual Studio version!

### ISSUE THREAD

**Issue by auner2456889** [laugh12321/TensorRT-YOLO#31]
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/111750539/dbfef897-a275-4648-874e-48fef883198f)
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/111750539/883f6b76-35e0-4904-8854-84d48ade56c8)
执行编译时出现错误
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/111750539/81b424f9-bf95-4a6a-8e25-d09412b43b10)

**Comment by auner2456889** [comment]
![image](https://github.com/laugh12321/TensorRT-YOLO/assets/111750539/338c7564-24ca-45a7-86cb-88a5600f4def)

**Comment by laugh12321** [comment]
在`xmake.lua`中加入`add_cuflags("-allow-unsupported-compiler")`

![image](https://github.com/laugh12321/TensorRT-YOLO/assets/38065710/a6000ab4-c82c-43a2-9991-9b16dd3934c4)

**Comment by FlypigW** [comment]
这里还有一种方案，也是不让其报错https://blog.csdn.net/lishiyu93/article/details/114599859
