### ISSUE TITLE
[Question]: 为什么不使用Python代码将ONNX转换为engine

### ISSUE THREAD

**Issue by dongming0920** [laugh12321/TensorRT-YOLO#33]
大佬  除了安装trt执行trtexec --onnx=models/best.onnx --saveEngine=models/best.engine --fp16， 有没有办法通过python版的trt通过代码转换呢。我需要部署到不同的客户端，打算直接给onnx，第一次运行的时候动态转换成engine。否则会出现算力不匹配问题

**Comment by laugh12321** [comment]
最开始的版本有写Python代码直接将onnx转换为engine。但是通过代码转换也必须要有TensorRT环境的，而且代码如果写的有问题在部署时也不好排查。在不同架构不同版本的TensorRT的客户端肯定要重新转换模型，与其这样还不如直接用官方的trtexec反正都要TensorRT环境。

也就是说只要导出一个onnx模型，在不同的设备重新专场engine就行，就不会出现架构不匹配的问题。

**Comment by dongming0920** [comment]
大佬有联系方式吗。想加你细聊一下，有偿

**Comment by laugh12321** [comment]
GitHub页面的联系方式私我，加微信
