### ISSUE TITLE
多写点教程

### ISSUE THREAD

**Issue by dyhisbig** [laugh12321/TensorRT-YOLO#35]
话说代码都开源了，就不能多写点教程吗。不愿不知道，一用各种问题

**Comment by laugh12321** [comment]
[文档教程](https://github.com/laugh12321/TensorRT-YOLO?tab=readme-ov-file#-%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B) 和 [视频](https://github.com/laugh12321/TensorRT-YOLO?tab=readme-ov-file#-bilibili) 都有，而且也有完整的[使用Docker的部署教程](https://www.bilibili.com/video/BV1Jr42137EP) 。 

每一步都有很详细的教程，就差把饭喂到嘴里了。如果你有难以解决的问题可以提issue或者私信问我，无论是在哪一个平台我都在认证解答，况且其他人都已经提了25个issue了请问哪一个没有解决？

**Comment by dyhisbig** [comment]
> [文档教程](https://github.com/laugh12321/TensorRT-YOLO?tab=readme-ov-file#-%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B) 和 [视频](https://github.com/laugh12321/TensorRT-YOLO?tab=readme-ov-file#-bilibili) 都有，而且也有完整的[使用Docker的部署教程](https://www.bilibili.com/video/BV1Jr42137EP) 。
> 
> 每一步都有很详细的教程，就差把饭喂到嘴里了。如果你有难以解决的问题可以提issue或者私信问我，无论是在哪一个平台我都在认真解答，况且其他人都已经提了25个issue了请问哪一个没有解决？

![图片](https://github.com/user-attachments/assets/04886519-7f5d-4bf6-b228-916d451db164)
实话实说，问题还是挺多，都无到有部署，折腾一晚上，最后卡在这了，哈哈哈
![图片](https://github.com/user-attachments/assets/24763bd1-a118-40af-84e0-c9fd47ca01d3)

用cpu能够tui理出结果图，但是加速不行，

**Comment by laugh12321** [comment]
你安装的包不是4.0版本的，4.0之前的版本使用 `cuda-python` 和 `tensorrt` python包推理。虽然也是GPU推理但是相较于C++版本慢了一倍多且没有实现cudaGraph加速。

去[Release](https://github.com/laugh12321/TensorRT-YOLO/releases)下载构建好的包，如果版本与你的环境不一样参考[快速编译安装](https://github.com/laugh12321/TensorRT-YOLO/blob/main/docs/cn/build_and_install.md) 自己构建，PyPI 还没有上传4.0版本的你估计是通过 PyPI 下载的。

**Comment by dyhisbig** [comment]
![图片](https://github.com/user-attachments/assets/6d20c98a-ecd0-4d54-94fe-ddef95929959)

**Comment by dyhisbig** [comment]
whl的4.0换上了，又来了新的问题

**Comment by laugh12321** [comment]
> ![图片](https://private-user-images.githubusercontent.com/87350092/350644905-6d20c98a-ecd0-4d54-94fe-ddef95929959.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MzgxMjYsIm5iZiI6MTcyMTQzNzgyNiwicGF0aCI6Ii84NzM1MDA5Mi8zNTA2NDQ5MDUtNmQyMGM5OGEtZWNkMC00ZDU0LTk0ZmUtZGRlZjk1OTI5OTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDAxMTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOThlNDljODY0ODA0MGQxM2Y4Mjg1NTg0MDEyMWMxYjcxNWQyNTE1MDdkY2MxZTQ3MDQ1ODE4MzA2MzVmM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-WkbQ0ctM67JfaFTKjlmfClPDt0Ab8yAUzNTPO8_9o)


你就没有好好看教程啊，教程写的很清楚【如果需要自己构建合适CUDA与TensorRT版本的 tensorrt_yolo 则需要先对 Deploy 进行编译，然后再按照以下步骤构建】，你都没有编译`Deploy`模块，libs下面当然什么都没有。麻烦认真看看教程，不要为了杠而杠。

![image](https://github.com/user-attachments/assets/88c34b43-6c7a-4302-809e-9778bdb416b9)

![image](https://github.com/user-attachments/assets/9c0f2a72-1d78-4526-90c2-390c40546705)

**Comment by dyhisbig** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/87350092/350644905-6d20c98a-ecd0-4d54-94fe-ddef95929959.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MzgxMjYsIm5iZiI6MTcyMTQzNzgyNiwicGF0aCI6Ii84NzM1MDA5Mi8zNTA2NDQ5MDUtNmQyMGM5OGEtZWNkMC00ZDU0LTk0ZmUtZGRlZjk1OTI5OTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDAxMTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOThlNDljODY0ODA0MGQxM2Y4Mjg1NTg0MDEyMWMxYjcxNWQyNTE1MDdkY2MxZTQ3MDQ1ODE4MzA2MzVmM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-WkbQ0ctM67JfaFTKjlmfClPDt0Ab8yAUzNTPO8_9o)
> 
> 你就没有好好看教程啊，教程写的很清楚【如果需要自己构建合适CUDA与TensorRT版本的 tensorrt_yolo 则需要先对 Deploy 进行编译，然后再按照以下步骤构建】，你都没有编译`Deploy`模块，libs下面当然什么都没有。麻烦认真看看教程，不要为了杠而杠。
> 
> ![image](https://private-user-images.githubusercontent.com/38065710/350650977-88c34b43-6c7a-4302-809e-9778bdb416b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzQzMTYsIm5iZiI6MTcyMTQ3NDAxNiwicGF0aCI6Ii8zODA2NTcxMC8zNTA2NTA5NzctODhjMzRiNDMtNmM3YS00MzAyLTgwOWUtOTc3OGJkYjQxNmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDExMTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOWNjZjI3MTdlNDQxMzRlYTM3NzJhZTAyNGFhZjBhYTNlYTQ3ZThhNmNjMjQ1ODkwYzUzMjRmZDc0ZjU1NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J69EJN4-WgAME6sdclNTLMJLKadQevpPsWpnJqp2P_w)
> 
> ![image](https://private-user-images.githubusercontent.com/38065710/350651238-9c0f2a72-1d78-4526-90c2-390c40546705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzQzMTYsIm5iZiI6MTcyMTQ3NDAxNiwicGF0aCI6Ii8zODA2NTcxMC8zNTA2NTEyMzgtOWMwZjJhNzItMWQ3OC00NTI2LTkwYzItMzkwYzQwNTQ2NzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDExMTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNGEwZGZiYzM1ZGNlYWY2ZDU2YWZiNjBmYzUzYmRiNGQzNGRjYzFiNTE3Mzk4MWM1NjMxYzZiYjFkY2I5YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LFaLWjKV9Z5sjM7BHsIqx7pojcGpAM2yo9qRw7KnW3Q)

首先感谢作者开源代码，能让我们底层的小喽啰有口饭吃，其次，我不明白作者为什么会认为我在杠，笑死，代码不行我换一个呗，如果你觉得提issue或者回答issue是一种负担，那么可以完全不理会，上文作者提到每一步都i有很详细的教程，给几条命令就是详细了，您是不是对教程有误解，让我把详细的错误贴出来，我按照你教程里pip安装3.0的代码，结果cuda没有，你说我安装的不是4.0，安装了4.0whl出现上述问题，您说我没有好好看教程，“【如果需要自己构建合适CUDA与TensorRT版本的 tensorrt_yolo 则需要先对 Deploy 进行编译，然后再按照以下步骤构建】”，我安装了4.0whl，那么我安装了4.0代码之后，如何才能知道什么时候需要自己构建合适CUDA与TensorRT版本的 tensorrt_yolo呢？代码一直报错是导入包有问题，去找相应文件没有，没编译肯定没有
作者可以找个身边的人，团体，或者公司里的，将这个代码，按照您所谓的教程进行部署，看看会不会遇到很多问题？
然后，建议作者将教程分个条理，而不是贴出几个命令，写个123总会变的清晰明了吧
最后，感谢作者对开源事业做出的贡献，再次感谢

**Comment by laugh12321** [comment]
首先，安装步骤就那几个命令。正常步骤是不会有问题的，我们团队和朋友也在用这个项目是没有问题的。

其次，我也没有觉得回答issue是一种负担，相反每一个提问的人我都在耐心解答。如果按你所说我觉得是负担大可不必理会提的issue。

再者，对于你说的认为你在杠的问题。开了issue后，不说明需要的问题只在抱怨，如果你是作者你会怎么想。

然后，关于你说的安装`whl` 3.0 与 4.0 版本的问题，我这里解释一下。首先3.0是的Python推理是完全使用`tensorrt`与`cuda-python`的python库实现 （没有cudaGraph加速），所有依赖仅需`pip`安装即可。然而，3.0版本的Python推理相较于C++慢了一倍不止。所以4.0版本将C++的`deploy`模块使用`pybind11`封装，故而4.0以及之后版本的`tensorrt_yolo`包的推理模块与CUDA、cuDNN、TensorRT版本强相关。我不可能把每一种组合的`whl`包都构建好去上传到PyPI，所以我只在PyPI上传了3.0及之前的版本，保留了最起码的可用性，在Release上发布了我指定版本的`whl`包 。而在README上已经明确说了，如若自行构建则需提前编译`Deploy`模块，可以肯定你因急于回复而忽略了这句话，这点从你给的问题截图就能证明。

最后，你提的关于教程的建议我这边会采纳，也欢迎每位使用者提出宝贵的意见，共同使得[TensorRT-YOLO](https://github.com/laugh12321/TensorRT-YOLO)这个项目越来越好。
