### ISSUE TITLE
[Help]: ImportError: libdeploy.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Saoforest** [laugh12321/TensorRT-YOLO#39]
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/9d2ffd56-c8da-499f-9869-7ba24b50e1fc">

**Comment by laugh12321** [comment]
@Saoforest 请告诉我你的操作流程，参考[安装 tensorrt_yolo](https://github.com/laugh12321/TensorRT-YOLO/blob/main/docs/cn/build_and_install.md#%E5%AE%89%E8%A3%85-tensorrt_yolo) 本地构建 `tensorrt_yolo` 前需要构建 `deploy` 模块。出现 `No such file or directory` 请先检查 `tensorrt_yolo/libs` 文件夹下是否有生成的动态库，若存在动态库则检查 `xmake.lua` 中设置的 `Python` 版本是否与当前使用环境的 `Python` 版本一致。

**Comment by Saoforest** [comment]
python 版本：
<img width="1164" alt="image" src="https://github.com/user-attachments/assets/77be0afa-5e2f-4a07-921b-1dfb71bec38e">

**Comment by laugh12321** [comment]
@Saoforest 直接使用[Release](https://github.com/laugh12321/TensorRT-YOLO/releases)中提前构建好的包的前提是在你的环境中以及配置了对应版本的`CUDA`与`TensorRT`以及`cuDNN`。

**Comment by laugh12321** [comment]
@Saoforest 没有问题的话它就关闭了。
