### ISSUE TITLE
Relationship Between TensorRT-YOLO Inference Precision Discrepancy and EfficientNMS Plugin Exported Engine

### ISSUE THREAD

**Issue by timarnoldev** [laugh12321/TensorRT-YOLO#40]
Running the exact same model (tested with v8, v9 and v10) with this library results in very bad detection results.
I converted them from .pt -> .onnx using `trtyolo` and the custom yolov10 repo respectively.

Some object classes aren't detected that all. Sometimes there are rare detections of random objects with very low confidences.
On the other hand running the model using tensorrt in python delivers perfect results.

TensorRT-YOLO
<img width="1598" alt="image" src="https://github.com/user-attachments/assets/e5dc9bea-e5e8-4c4b-aa64-435669345986">

Python Tensorrt Inference
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/4af0c715-d959-47d2-b1b6-ff46c1ac763b">

Any ideas what the problem might be?

Export command I used:

`trtyolo export -w best.pt -v yolov8 -o output --max_boxes 100 --iou_thres 0.45 --conf_thres 0.15 -b -1`

**Comment by laugh12321** [comment]
@timarnoldev Below is an inference accuracy comparison using YOLOv8s as an example. It can be observed that TensorRT-YOLO inference `engine` has slight accuracy loss compared to Ultralytics inference `pt`. The preprocessing methods used in `tensorrt_yolo` version 3.0 and TensorRT-YOLO are [`letterbox`](https://github.com/laugh12321/TensorRT-YOLO/blob/fdd9a9b053b2b35170b17a9f864ccd0f893765a3/tensorrt_yolo/infer/general.py#L59) and [`gpuBilinearWarpAffine`](https://github.com/laugh12321/TensorRT-YOLO/blob/cd41f0ae378dd55fe847f3973525411f93ea23ce/source/deploy/vision/cudaWarp.cu#L11C17-L11C38) respectively. Their inference results show consistent accuracy, and the implementation of `letterbox` in `tensorrt_yolo` version 3.0 is derived from Ultralytics' [`LetterBox`](https://github.com/ultralytics/ultralytics/blob/9f22f45189bd32efc14ddcb7b7b42a548b7aef6f/examples/YOLOv8-OpenCV-int8-tflite-Python/main.py#L31). Therefore, it can be concluded that the main cause of accuracy loss in inference is due to the `engine` exported by `trtexec` with the Efficient NMS Plugin. Reference: [Efficient NMS Plugin Limitations](https://github.com/NVIDIA/TensorRT/tree/release/10.2/plugin/efficientNMSPlugin#limitations).

As for the significant accuracy discrepancy you have shown, I find it puzzling. Please check if your processing workflow is consistent with mine.

### Ultralytics FP16

```python
from ultralytics import YOLO
model = YOLO("D:/Models/YOLOv8/yolov8s.pt")
model.predict("D:/Downloads/coco128/images/train2017/000000000077.jpg", save=True, imgsz=640, conf=0.25, iou=0.45, max_det=100, half=True, device="0")
```

![000000000077](https://github.com/user-attachments/assets/9a79710d-9024-41c2-8d26-ff6973bafc46)

### Ultralytics FP32

```python
from ultralytics import YOLO
model = YOLO("D:/Models/YOLOv8/yolov8s.pt")
model.predict("D:/Downloads/coco128/images/train2017/000000000077.jpg", save=True, imgsz=640, conf=0.25, iou=0.45, max_det=100, device="0")
```

![000000000077](https://github.com/user-attachments/assets/bae2fced-0f92-498f-8af3-83615433431c)

### TensorRT-YOLO FP16

```sh
trtyolo export -w yolov8s.pt -v yolov8 --imgsz 640 -b 1 --max_boxes 100 --iou_thres 0.45 --conf_thres 0.25 -o ./ -s
trtexec --onnx=yolov8s.onnx --saveEngine=yolov8s-fp16.engine --fp16
xmake run -P . detect -e D:/Models/YOLOv8/yolov8s-fp16.engine -i D:/Downloads/coco128/images/train2017/000000000077.jpg -o ./ -l labels.txt
```

![000000000077-fp16](https://github.com/user-attachments/assets/944506fa-b245-42f6-b2ea-98454161e21d)

### TensorRT-YOLO FP32

```sh
trtyolo export -w yolov8s.pt -v yolov8 --imgsz 640 -b 1 --max_boxes 100 --iou_thres 0.45 --conf_thres 0.25 -o ./ -s
trtexec --onnx=yolov8s.onnx --saveEngine=yolov8s-fp32.engine
xmake run -P . detect -e D:/Models/YOLOv8/yolov8s-fp32.engine -i D:/Downloads/coco128/images/train2017/000000000077.jpg -o ./ -l labels.txt
```

![000000000077-fp32](https://github.com/user-attachments/assets/39afa56e-360f-4ff7-a90d-87ee4aed0691)

### trtyolo 3.0.2 FP16

```sh
pip install tensorrt_yolo
trtyolo export -w yolov8s.pt -v yolov8 --imgsz 640 -b 1 --max_boxes 100 --iou_thres 0.45 --conf_thres 0.25 -o ./ -s
trtexec --onnx=yolov8s.onnx --saveEngine=yolov8s-fp16.engine --fp16
trtyolo infer -e D:/Models/YOLOv8/yolov8s-fp16.engine -i D:/Downloads/coco128/images/train2017/000000000077.jpg -o ./ -l labels.txt
```

![000000000077-py16](https://github.com/user-attachments/assets/d56f8e1d-aa5f-450e-ba05-793a495149a6)

### trtyolo 3.0.2 FP32

```sh
pip install tensorrt_yolo
trtyolo export -w yolov8s.pt -v yolov8 --imgsz 640 -b 1 --max_boxes 100 --iou_thres 0.45 --conf_thres 0.25 -o ./ -s
trtexec --onnx=yolov8s.onnx --saveEngine=yolov8s-fp32.engine
trtyolo infer -e D:/Models/YOLOv8/yolov8s-fp32.engine -i D:/Downloads/coco128/images/train2017/000000000077.jpg -o ./ -l labels.txt
```

![000000000077-py32](https://github.com/user-attachments/assets/c3231fe2-0cd8-4ba6-8d91-3a8b8cf483cc)

**Comment by timarnoldev** [comment]
Thanks for your detailed reply @laugh12321 
I use the engine file for the python version as well as the c++ version but with your EfficientNMS plugin as discussed in #38 
Is it mandatory to use this plugin? Nvidia seems to have deprecated it: https://github.com/NVIDIA/TensorRT/blob/release/10.1/plugin/efficientNMSPlugin/README.md

Maybe the problem is in the way preprocessing is handled. I used Roboflow for dataset preparation which compresses the images down to 640x640. How is image scaling managed in TonsorRT-YOLO?

**Comment by laugh12321** [comment]
@timarnoldev For the TensorRT-YOLO project, the EfficientNMS plugin is mandatory. It replaces the use of CUDA Kernels for post-processing, thereby improving inference speed. In future versions, we will consider replacing the EfficientNMS plugin with the INMSLayer.

Regarding the preprocessing operations mentioned for Roboflow, I am not very familiar with them. I use the same preprocessing method as Ultralytics, which involves scaling the images while maintaining the aspect ratio. You can refer to this article for more information: https://medium.com/@mattia.digiusto/optimising-image-pre-processing-in-python-ac9157951bf6

**Comment by timarnoldev** [comment]
> Regarding the preprocessing operations mentioned for Roboflow, I am not very familiar with them. I use the same preprocessing method as Ultralytics, which involves scaling the images while maintaining the aspect ratio. You can refer to this article for more information: https://medium.com/@mattia.digiusto/optimising-image-pre-processing-in-python-ac9157951bf6

I just checked, I'm also using letterbox for the python program.
Btw this is how i converted .pt > .onnx back then: https://github.com/triple-Mu/YOLOv8-TensorRT?tab=readme-ov-file#export-end2end-onnx-with-nms

**Comment by laugh12321** [comment]
@timarnoldev The conversion methods for TensorRT-YOLO and YOLOv8-TensorRT models are the same, and the inference results are identical.

**Convert with YOLOv8-TensorRT, Inference with TensorRT-YOLO FP16**

```sh
git clone https://github.com/triple-Mu/YOLOv8-TensorRT.git
cd YOLOv8-TensorRT
python export-det.py --weights D:\Models\YOLOv8\yolov8s.pt --iou-thres 0.45 --conf-thres 0.25 --topk 100 --opset 11 --sim --input-shape 1 3 640 640 --device cuda:0
cd D:\Models\YOLOv8
trtexec --onnx=yolov8s.onnx --saveEngine=yolov8s-fp16.engine --fp16
xmake run -P . detect -e D:/Models/YOLOv8/yolov8s-fp16.engine -i D:/Downloads/coco128/images/train2017/000000000077.jpg -o ./ -l labels.txt
```

![000000000077](https://github.com/user-attachments/assets/6cafb071-2690-4ef9-a3ca-0c7feb2adeaa)

**Comment by timarnoldev** [comment]
Good to know, thank you.
Can the tensorrt version be the issue?
With python I used 8.6.1 and now 10.2.0
I'm so confused right now because in both ways I used the exact same .pt file.

**Comment by laugh12321** [comment]
@timarnoldev It shouldn't be an issue with the TensorRT version. The precision should be the same between 8.6.1 and 10.2.0. To better diagnose the problem, could you please send me your .pt model and test data in a ZIP archive? This way, I can help you analyze it in more detail.

**Comment by timarnoldev** [comment]
[best.pt.zip](https://github.com/user-attachments/files/16486761/best.pt.zip)
[YOLO.zip](https://github.com/user-attachments/files/16486762/YOLO.zip)

I also just found out, triple-Mu/YOLOv8-TensorRT also has a c++ inference example. This works just fine with the expected results, but only supports yolov8.

**Comment by laugh12321** [comment]
![image](https://github.com/user-attachments/assets/a1758e9b-35cc-4ba3-9eb0-92e375f4e376)
[vis.zip](https://github.com/user-attachments/files/16486850/vis.zip)

@timarnoldev I used the provided model and data to perform inference with TensorRT-YOLO, and the accuracy of the results is normal. The vis.zip file contains the visualized results of the inference.

**Comment by timarnoldev** [comment]
That is strange. This is the code I used for inference. Is maybe here the problem?

```c++
#include <QCoreApplication>
#include <iostream>
#include <opencv2/opencv.hpp>
#include "AIWorker.h"
#include "tensorrt/deploy/vision/detection.hpp"

AIWorker::AIWorker(QObject *parent)
        : QObject(parent) {
    m_running = false;
}

std::vector<std::pair<std::string, cv::Scalar>> generateLabelColorPairs() {
    std::vector<std::pair<std::string, cv::Scalar>> labelColorPairs;


    auto generateRandomColor = []() {
        std::random_device                 rd;
        std::mt19937                       gen(rd());
        std::uniform_int_distribution<int> dis(0, 255);
        return cv::Scalar(dis(gen), dis(gen), dis(gen));
    };


    labelColorPairs.emplace_back("ball", generateRandomColor());
    labelColorPairs.emplace_back("player_red", generateRandomColor());

    return labelColorPairs;
}

// Visualize detection results
void visualize(cv::Mat& image, const deploy::DetectionResult& result, const std::vector<std::pair<std::string, cv::Scalar>>& labelColorPairs) {
    for (size_t i = 0; i < result.num; ++i) {
        const auto& box       = result.boxes[i];
        int         cls       = result.classes[i];
        float       score     = result.scores[i];
        const auto& label     = labelColorPairs[cls].first;
        const auto& color     = labelColorPairs[cls].second;
        std::string labelText = label + " " + cv::format("%.2f", score);

        // Draw rectangle and label
        int      baseLine;
        cv::Size labelSize = cv::getTextSize(labelText, cv::FONT_HERSHEY_SIMPLEX, 0.6, 1, &baseLine);
        cv::rectangle(image, cv::Point(box.left, box.top), cv::Point(box.right, box.bottom), color, 2, cv::LINE_AA);
        cv::rectangle(image, cv::Point(box.left, box.top - labelSize.height), cv::Point(box.left + labelSize.width, box.top), color, -1);
        cv::putText(image, labelText, cv::Point(box.left, box.top), cv::FONT_HERSHEY_SIMPLEX, 0.6, cv::Scalar(255, 255, 255), 1);
    }
}

void AIWorker::Start() {
    m_running = true;

    std::shared_ptr<deploy::BaseDet> model = std::make_shared<deploy::DeployDet>("../ai.engine");
    std::vector<std::pair<std::string, cv::Scalar>> labels = generateLabelColorPairs();

    while (m_running) {
        QCoreApplication::processEvents( QEventLoop::WaitForMoreEvents,1);

        deploy::Image image(currentImage.data, currentImage.cols, currentImage.rows);
        auto result = model->predict(image);
        visualize(currentImage, result, labels);

        emit imageAnalyzed(currentImage, currentImageID);
        //cv::imshow("AI", currentImage);

        nextid++;

    }
}

int AIWorker::getCurrentImageId() {
    return nextid;
}

void AIWorker::onImageReceivedAr(cv::Mat image, int id) {

    this->currentImage = image.clone();
    this->currentImageID = id;
    this->imagePresent = true;
}

void AIWorker::stop() {
    m_running = false;

}
```

**Comment by laugh12321** [comment]
@timarnoldev You might want to first try using [TensorRT-YOLO's demo/detect](https://github.com/laugh12321/TensorRT-YOLO/tree/main/demo/detect) to verify if the accuracy is correct. All the C++ inference results we discussed earlier were obtained using this `demo/detect`.

**Comment by laugh12321** [comment]
> Thanks for your detailed reply @laugh12321 I use the engine file for the python version as well as the c++ version but with your EfficientNMS plugin as discussed in #38 Is it mandatory to use this plugin? Nvidia seems to have deprecated it: https://github.com/NVIDIA/TensorRT/blob/release/10.1/plugin/efficientNMSPlugin/README.md
> 
> Maybe the problem is in the way preprocessing is handled. I used Roboflow for dataset preparation which compresses the images down to 640x640. How is image scaling managed in TonsorRT-YOLO?

@timarnoldev To clarify, NVIDIA/TensorRT has deprecated the `EfficientNMSONNXPlugin` plugin, not the `EfficientNMS_TRT` plugin. In fact, the `efficientNMSPlugin` defines two plugins: `EfficientNMS_TRT` and `EfficientNMSONNXPlugin`.

Based on testing, the inference accuracy is consistent whether using `EfficientNMS_TRT`, `EfficientNMSONNXPlugin`, or `INMSLayer`.

**Comment by timarnoldev** [comment]
I just found the problem. I preprocessed the images on myself which didn't line up with the training. Thank you very much for your help.

**Comment by zoulee24** [comment]
how to use INMSLayer instead of EfficientNMS_TRT?

**Comment by zoulee24** [comment]
> @zoulee24 你用 ONNX 的 [NonMaxSuppression](https://onnx.ai/onnx/operators/onnx__NonMaxSuppression.html) 算子在构建引擎时自动会被解析为 INMSLayer，具体参考这个回答[NVIDIA/TensorRT#3807 (comment)](https://github.com/NVIDIA/TensorRT/issues/3807#issuecomment-2067550187)

明白了，我尝试用yolov6中的[ORT_NMS](https://github.com/meituan/YOLOv6/blob/main/yolov6/models/end2end.py)来导出[NonMaxSuppression](https://onnx.ai/onnx/operators/onnx__NonMaxSuppression.html)，但是不知道为什么通过netron看到有一个if分支，它导致了无法转换为tensorRT，之前我也用过yolov6是没问题的。
![image](https://github.com/user-attachments/assets/882e21ca-8caa-4fb1-b1d6-6c95a7b28656)

**Comment by zoulee24** [comment]
这是我的代码，只修改了 yolov6 物体置信度的位置，因为yolo11没有物体置信度
```python
class ORT_NMS(torch.autograd.Function):
    '''ONNX-Runtime NMS operation'''
    @staticmethod
    def forward(ctx,
                boxes,
                scores,
                max_output_boxes_per_class=torch.tensor([100]),
                iou_threshold=torch.tensor([0.45]),
                score_threshold=torch.tensor([0.25])):
        device = boxes.device
        batch = scores.shape[0]
        num_det = random.randint(0, 100)
        batches = torch.randint(0, batch, (num_det,)).sort()[0].to(device)
        idxs = torch.arange(100, 100 + num_det).to(device)
        zeros = torch.zeros((num_det,), dtype=torch.int64).to(device)
        selected_indices = torch.cat([batches[None], zeros[None], idxs[None]], 0).T.contiguous()
        selected_indices = selected_indices.to(torch.int64)
        return selected_indices

    @staticmethod
    def symbolic(g, boxes, scores, max_output_boxes_per_class, iou_threshold, score_threshold):
        return g.op("NonMaxSuppression", boxes, scores, max_output_boxes_per_class, iou_threshold, score_threshold)


class UltralyticsDetect(Detect):
    def forward(self, x):
        """Concatenates and returns predicted bounding boxes and class probabilities."""
        if self.end2end:
            return self.forward_end2end(x)

        for i in range(self.nl):
            x[i] = torch.cat((self.cv2[i](x[i]), self.cv3[i](x[i])), 1)
        dbox, cls = self._inference(x)

        return self.nms(dbox.transpose(1, 2), cls.transpose(1, 2))

    def nms(self, box, score):
        batch = box.shape[0]
        convert_matrix = torch.tensor(
            [[1, 0, 1, 0], [0, 1, 0, 1], [-0.5, 0, 0.5, 0], [0, -0.5, 0, 0.5]],
            dtype=torch.float32,
            device=box.device,
            requires_grad=False
        )
        nms_box = box @ convert_matrix
        nms_score = score.transpose(1, 2).contiguous()

        selected_indices = ORT_NMS.apply(
            nms_box, nms_score, 
            torch.tensor([self.max_det], dtype=torch.int64), 
            torch.tensor([self.iou_thres], dtype=torch.float32), 
            torch.tensor([self.conf_thres], dtype=torch.float32),
        )
        batch_inds, cls_inds, box_inds = selected_indices.unbind(1)
        selected_score = nms_score[batch_inds, cls_inds, box_inds].unsqueeze(1)
        selected_box = nms_box[batch_inds, box_inds, ...]

        dets = torch.cat([selected_box, selected_score], dim=1)

        batched_dets = dets.unsqueeze(0).repeat(batch, 1, 1)
        batch_template = torch.arange(
            0, batch, dtype=batch_inds.dtype, device=batch_inds.device
        )
        batched_dets = batched_dets.where(
            (batch_inds == batch_template.unsqueeze(1)).unsqueeze(-1),
            batched_dets.new_zeros(1),
        )

        batched_labels = cls_inds.unsqueeze(0).repeat(batch, 1)
        batched_labels = batched_labels.where(
            (batch_inds == batch_template.unsqueeze(1)), batched_labels.new_ones(1) * -1
        )

        N = batched_dets.shape[0]

        batched_dets = torch.cat((batched_dets, batched_dets.new_zeros((N, 1, 5))), 1)
        batched_labels = torch.cat(
            (batched_labels, -batched_labels.new_ones((N, 1))), 1
        )

        _, topk_inds = batched_dets[:, :, -1].sort(dim=1, descending=True)

        topk_batch_inds = torch.arange(
            batch, dtype=topk_inds.dtype, device=topk_inds.device
        ).view(-1, 1)
        batched_dets = batched_dets[topk_batch_inds, topk_inds, ...]
        det_classes = batched_labels[topk_batch_inds, topk_inds, ...]
        det_boxes, det_scores = batched_dets.split((4, 1), -1)
        det_scores = det_scores.squeeze(-1)
        num_det = (det_scores > 0).sum(1, keepdim=True)
        return num_det, det_boxes, det_scores, det_classes
```

**Comment by zoulee24** [comment]
在TensorRT10上 EfficientNMS_TRT 无法找到插件，可能需要单独安装或者什么，我看官方说已经在[TensorRT9](https://github.com/NVIDIA/TensorRT/blob/release/10.1/plugin/efficientNMSPlugin/README.md)废弃这个插件了

**Comment by laugh12321** [comment]
@zoulee24 

- 首先，TensorRT 的各个版本都是支持 [EfficientNMS_TRT](https://github.com/NVIDIA/TensorRT/tree/release/10.6/plugin/efficientNMSPlugin) 的，只不过在 9.0 将废弃其中 `EfficientNMS_ONNX_TRT` （`EfficientNMS_TRT` 与 `EfficientNMS_ONNX_TRT` 是两个插件）, 如果需要使用 `EfficientNMS_ONNX_TRT` 请用 `INMSLayer` 替代。

![image](https://github.com/user-attachments/assets/95d3d83f-cea0-49df-a17b-64afdebbfc78)

- 其次，如果你只是在 NVIDIA 设备上进行部署的话，这里建议使用 `EfficientNMS_TRT` 来加速后处理。我这边经过测试`EfficientNMS_TRT` 的速度要比 `EfficientNMS_ONNX_TRT` 与 `INMSLayer` 快，因为后两者返回的是索引还需要二次处理，并且 `INMSLayer` 存在与硬件相关的限制 K。（详细请参考 [nvinfer1::INMSLayer Class Reference](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_n_m_s_layer.html) 中的 Warning ）

- 最后，关于你说的使用 [meituan/YOLOv6 ORT_NMS](https://github.com/meituan/YOLOv6/blob/main/yolov6/models/end2end.py#L140) 导出的 ONNX 存在 `if` 分支导致无法被转换为 TensorRT 引擎，通过与你发的结构图对比是由[源代码的188行](https://github.com/meituan/YOLOv6/blob/main/yolov6/models/end2end.py#L188)引起的分支判断，这里你尝试自行修改，原因已经告诉你了。
