### ISSUE TITLE
[Help]: xmake 编译 `demo/detect/detect.cpp` 报错 error: Invalid option: --deploy

### ISSUE THREAD

**Issue by retioa11** [laugh12321/TensorRT-YOLO#42]
参考这个文档：
![image](https://github.com/user-attachments/assets/9bf2746c-477b-4db3-a003-396c8ab40e35)
使用的命令：
xmake f -P . --tensorrt="F:/ThirdPartyLibrary/TensorRT-8.6.1.6.Windows10.x86_64.cuda-11.8" --deploy=F:/TensorrtYolo/TensorRT-YOLO-main0809
报错：
![image](https://github.com/user-attachments/assets/d8e4cf8b-67c3-4f10-b21d-04480ca96e4b)
大佬可否指点一下，怎么解决？

**Comment by laugh12321** [comment]
@retioa11 还有问题吗？没有问题就关闭了。

**Comment by retioa11** [comment]
没问题了，可以了，谢谢。很抱歉，没有及时回复。
