### ISSUE TITLE
[Question]: 能否在自己的 Python 项目中调用该库进行目标检测并获取结果？

### ISSUE THREAD

**Issue by WaHa-World** [laugh12321/TensorRT-YOLO#43]

**Comment by laugh12321** [comment]
可以的，只需要参考[快速编译安装](https://github.com/laugh12321/TensorRT-YOLO/blob/main/docs/cn/build_and_install.md)构建好python包即可。(需要先编译Deploy模块，如果需要推理OBB则还需参考[构建 TensorRT 自定义插件](https://github.com/laugh12321/TensorRT-YOLO/blob/main/docs/cn/build_trt_custom_plugin.md)编译带自定义插件的TensorRT)

**Comment by laugh12321** [comment]
@WaHa-World 没有问题的话就关闭了。
