### ISSUE TITLE
[Help]: YOLOv8-OBB 的 ONNX 无法导出

### ISSUE THREAD

**Issue by wuaman** [laugh12321/TensorRT-YOLO#46]
通过pip install tensorrt-yolo安装后，导出onnx报错：YOLO version 'yolov8' detect head not supported!
yolov8n-obb.pt下载自https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n-obb.pt
望大佬抽空回答，不胜感激
![image](https://github.com/user-attachments/assets/93947a91-4566-4cbe-852a-dd32735822f4)

**Comment by laugh12321** [comment]
@wuaman PiPy 上面的是4.0老版本，新版本需要自己构建才能导出和推理obb，具体的看文档和B站视频
