### ISSUE TITLE
[Help]: Failed to detect a default CUDA architecture.

### ISSUE THREAD

**Issue by cll-git** [laugh12321/TensorRT-YOLO#47]
Thanks for you contributions for the community. 

However, I meat an error " Failed to detect a default CUDA architecture " when I run command " cmake -DTENSORRT_PATH=/usr/src/tensorrt ..". 

Do you have any solution on it?

**Comment by laugh12321** [comment]
@cll-git 先确定你有没有安装 CUDA Toolkit, 如何安装了还是有这个报错可以参考这个链接解决。https://www.cnblogs.com/metaz/p/16919028.html

**Comment by cll-git** [comment]
我用的是jetson上的cuda，同时按照NVIDIA的官方教程，确认正确安装了cuda了的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月17日(星期四) 下午5:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [laugh12321/TensorRT-YOLO] [Help]: Failed to detect a default CUDA architecture. (Issue #47)














 
@cll-git 先确定你有没有安装 CUDA Toolkit, 如果安装了还是有这个报错可以参考这个链接解决。https://www.cnblogs.com/metaz/p/16919028.html

**Comment by laugh12321** [comment]
@cll-git 看看输入 `nvcc --version` 是否正常，加上 `-DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc` 试试。

**Comment by cll-git** [comment]
感谢，已解决。是由于jetson设备的CUDA是jetpack自动安装的，所以我忘记在bashrc里面添加cuda的路径了，添加上去就正常了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月17日(星期四) 下午5:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [laugh12321/TensorRT-YOLO] [Help]: Failed to detect a default CUDA architecture. (Issue #47)














 
@cll-git 看看输入 nvcc --version 是否正常，加上 -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc 试试。

**Comment by laugh12321** [comment]
@cll-git 没事，问题解决了就行。这个issue就关闭了。
