### ISSUE TITLE
[Question]: Jetson 等边缘设备上如何适配低版本CUDA与TensorRT

### ISSUE THREAD

**Issue by cll-git** [laugh12321/TensorRT-YOLO#48]
看简介要求CUDA和TensorRT有比较高的版本要求，但是边缘设备尝试了多次仍然难以更新，想问下是否有适配较低版本的CUDA和TensorRT的计划？或者自己修改的话，主要从哪入手？谢谢

**Comment by laugh12321** [comment]
@cll-git 首先不会去适配低版本，因为官方已经弃用了，而且这个项目在很早之前就是用的低版本的API实现的。

关于你说的在jetson上升级的问题，我记得最新版本的JetPack是可以支持的。只要CUDA版本不低于11，TensorRT版本不低于8.6.1即可。现在大部分JetPack所提供的CUDA版本是可以满足我说的要求的，你只需要另外再下载一个TensorRT包即可。

**Comment by cll-git** [comment]
昨天试了几次更新cuda和tensorrt，都没成功，今天换了安装方法，就可以更新了
