### ISSUE TITLE
Docker部署报错

### ISSUE THREAD

**Issue by DefconBird** [laugh12321/TensorRT-YOLO#51]
作者你好，非常感谢你的贡献，但是我在参考你的B站教程时，遇到了困难（https://www.bilibili.com/video/BV1Jr42137EP）

![image](https://github.com/user-attachments/assets/cf8008e6-0218-4082-8d54-e9a8a1c8f4ba)
报错：
![image](https://github.com/user-attachments/assets/672a3fa5-2adc-47da-9918-a20c6d7b7141)
应该如何解决呢，感谢

**Comment by laugh12321** [comment]
@DefconBird 试一下这个[使用 Xmake 编译](https://github.com/laugh12321/TensorRT-YOLO/blob/main/docs/cn/build_and_install.md#%E4%BD%BF%E7%94%A8-xmake-%E7%BC%96%E8%AF%91)

**Comment by DefconBird** [comment]
> @DefconBird 试一下这个[使用 Xmake 编译](https://github.com/laugh12321/TensorRT-YOLO/blob/main/docs/cn/build_and_install.md#%E4%BD%BF%E7%94%A8-xmake-%E7%BC%96%E8%AF%91)

仍然报错：
`root@asuka-HP-Pavilion-Gaming-Desktop-790-07xx:/home/TensorRT-YOLO# xmake f --tensorrt="/usr/local/tensorrt"
xmake v2.9.6+20241030, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io
    
    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor
    

Usage: $xmake config|f [options] [target]

Configure the project.

Common options:
    -q, --quiet                            Quiet operation.
    -y, --yes                              Input yes by default if need user confirm.
        --confirm=CONFIRM                  Input the given result if need user confirm.
                                               - yes
                                               - no
                                               - def
    -v, --verbose                          Print lots of verbose information for users.
        --root                             Allow to run xmake as root.
    -D, --diagnosis                        Print lots of diagnosis information (backtrace, check info ..) only for developers.
                                           And we can append -v to get more whole information.
                                               e.g. $ xmake -vD
    -h, --help                             Print this help message and exit.

    -F FILE, --file=FILE                   Read a given xmake.lua file.
    -P PROJECT, --project=PROJECT          Change to the given project directory.
                                           Search priority:
                                               1. The Given Command Argument
                                               2. The Envirnoment Variable: XMAKE_PROJECT_DIR
                                               3. The Current Directory

Command options (config):
    -c, --clean                            Clean the cached user configs and detection cache.
        --check                            Just ignore detection cache and force to check all, it will reserve the cached user configs.
        --export=EXPORT                    Export the current configuration to the given file.
                                               e.g.
                                               - xmake f -m debug -xxx=y --export=build/config.txt
        --import=IMPORT                    Import configs from the given file.
                                               e.g.
                                               - xmake f -import=build/config.txt
        --menu                             Configure project with a menu-driven user interface.

    -p PLAT, --plat=PLAT                   Compile for the given platform. (default: auto)
                                               - msys
                                               - cross
                                               - windows
                                               - appletvos
                                               - macosx
                                               - bsd
                                               - harmony
                                               - applexros
                                               - android
                                               - wasm
                                               - cygwin
                                               - linux
                                               - watchos
                                               - mingw
                                               - iphoneos
                                               - haiku
    -a ARCH, --arch=ARCH                   Compile for the given architecture. (default: auto)
                                               - msys: i386 x86_64
                                               - cross: i386 x86_64 arm arm64 mips mips64 riscv riscv64 loong64 s390x ppc ppc64 sh4
                                               - windows: x86 x64 arm arm64 arm64ec
                                               - appletvos: arm64 armv7 armv7s i386 x86_64
                                               - macosx: x86_64 arm64
                                               - bsd: i386 x86_64
                                               - harmony: armeabi-v7a arm64-v8a x86 x86_64
                                               - applexros: arm64 armv7 armv7s i386 x86_64
                                               - android: armeabi armeabi-v7a arm64-v8a x86 x86_64 mips mip64
                                               - wasm: wasm32 wasm64
                                               - cygwin: i386 x86_64
                                               - linux: i386 x86_64 armv7 armv7s arm64-v8a mips mips64 mipsel mips64el loong64
                                               - watchos: armv7k i386
                                               - mingw: i386 x86_64 arm arm64
                                               - iphoneos: arm64 x86_64
                                               - haiku: i386 x86_64
    -m MODE, --mode=MODE                   Compile for the given mode. (default: auto)
                                               - debug
                                               - release
    -k KIND, --kind=KIND                   Compile for the given target kind. (default: static)
                                               - static
                                               - shared
                                               - binary
        --host=HOST                        Set the current host environment. (default: linux)
        --policies=POLICIES                Set the project policies.
                                               e.g.
                                               - xmake f --policies=package.fetch_only
                                               - xmake f --policies=package.precompiled:n,package.install_only

Command options (Package Configuration):
        --require=REQUIRE                  Require all dependent packages?
                                               - yes
                                               - no
        --pkg_searchdirs=PKG_SEARCHDIRS    The search directories of the remote package.
                                               e.g.
                                               - xmake f --pkg_searchdirs=/dir1:/dir2

Command options (Cross Complation Configuration):
        --cross=CROSS                      Set cross toolchains prefix
                                           e.g.
                                               - i386-mingw32-
                                               - arm-linux-androideabi-
        --target_os=TARGET_OS              Set target os only for cross-complation
        --bin=BIN                          Set cross toolchains bin directory
                                           e.g.
                                               - sdk/bin (/arm-linux-gcc ..)
        --sdk=SDK                          Set cross SDK directory
                                           e.g.
                                               - sdk/bin
                                               - sdk/lib
                                               - sdk/include
        --toolchain=TOOLCHAIN              Set toolchain name
                                           e.g. 
                                               - xmake f --toolchain=clang
                                               - xmake f --toolchain=[cross|llvm|sdcc ..] --sdk=/xxx
                                               - run `xmake show -l toolchains` to get all toolchains
        --toolchain_host=TOOLCHAIN_HOST    Set host toolchain name, it's only for building packages on host machine.
                                           e.g. 
                                               - xmake f --toolchain_host=clang
                                               - xmake f --toolchain_host=[cross|llvm|sdcc ..] --sdk=/xxx
                                               - run `xmake show -l toolchains` to get all toolchains
        --runtimes=RUNTIMES                Set the compiler runtime library.
                                           e.g. 
                                               - xmake f --runtimes=MTd
                                               - xmake f --runtimes=MT,c++_static
                                               - MT
                                               - MTd
                                               - MD
                                               - MDd
                                               - c++_static
                                               - c++_shared
                                               - stdc++_static
                                               - stdc++_shared
                                               - gnustl_static
                                               - gnustl_shared
                                               - stlport_static
                                               - stlport_shared
        --go=GO                            The Golang Compiler
        --gcld=GCLD                        The Golang Linker
        --go-ar=GO-AR                      The Golang Static Library Linker
        --links=LINKS                      The Link Libraries
        --syslinks=SYSLINKS                The System Link Libraries
        --linkdirs=LINKDIRS                The Link Search Directories
        --includedirs=INCLUDEDIRS          The Include Search Directories
        --cxx=CXX                          The C++ Compiler
        --cpp=CPP                          The C/C++ Preprocessor
        --ld=LD                            The Linker
        --ar=AR                            The Static Library Linker
        --sh=SH                            The Shared Library Linker
        --ranlib=RANLIB                    The Static Library Index Generator
        --cxflags=CXFLAGS                  The C/C++ compiler Flags
        --cxxflags=CXXFLAGS                The C++ Compiler Flags
        --ldflags=LDFLAGS                  The Binary Linker Flags
        --arflags=ARFLAGS                  The Static Library Linker Flags
        --shflags=SHFLAGS                  The Shared Library Linker Flags
        --frameworks=FRAMEWORKS            The Frameworks
        --frameworkdirs=FRAMEWORKDIRS      The Frameworks Search Directories
        --mm=MM                            The Objc Compiler
        --mxx=MXX                          The Objc++ Compiler
        --mflags=MFLAGS                    The Objc Compiler Flags
        --mxflags=MXFLAGS                  The Objc/c++ Compiler Flags
        --mxxflags=MXXFLAGS                The Objc++ Compiler Flags
        --dc=DC                            The Dlang Compiler
        --dcld=DCLD                        The Dlang Linker
        --dcar=DCAR                        The Dlang Static Library Archiver
        --dcsh=DCSH                        The Dlang Shared Library Linker
        --as=AS                            The Assembler
        --asflags=ASFLAGS                  The Assembler Flags
        --pc=PC                            The Pascal Compiler
        --pcld=PCLD                        The Pascal Linker
        --pcsh=PCSH                        The Pascal Shared Library Linker
        --nc=NC                            The Nim Compiler
        --ncld=NCLD                        The Nim Linker
        --ncar=NCAR                        The Nim Static Library Archiver
        --ncsh=NCSH                        The Nim Shared Library Linker
        --mrc=MRC                          The Microsoft Resource Compiler
        --mrcflags=MRCFLAGS                The Microsoft Resource Flags
        --sc=SC                            The Swift Compiler
        --scld=SCLD                        The Swift Linker
        --scsh=SCSH                        The Swift Shared Library Linker
        --cu=CU                            The Cuda Compiler
        --cu-ccbin=CU-CCBIN                The Cuda Host C++ Compiler
        --culd=CULD                        The Cuda Linker
        --cuflags=CUFLAGS                  The Cuda Compiler Flags
        --culdflags=CULDFLAGS              The Cuda Linker Flags
        --rc=RC                            The Rust Compiler
        --rcld=RCLD                        The Rust Linker
        --rcar=RCAR                        The Rust Static Library Archiver
        --rcsh=RCSH                        The Rust Shared Library Linker
        --cc=CC                            The C Compiler
        --cflags=CFLAGS                    The C Compiler Flags
        --zc=ZC                            The Zig Compiler
        --zcld=ZCLD                        The Zig Linker
        --zcar=ZCAR                        The Zig Static Library Archiver
        --zcsh=ZCSH                        The Zig Shared Library Linker
        --fc=FC                            The Fortran Compiler
        --fcld=FCLD                        The Fortran Linker
        --fcsh=FCSH                        The Fortran Shared Library Linker

Command options (Android Configuration):
        --ndk=NDK                          The NDK Directory
        --ndk_sdkver=NDK_SDKVER            The SDK Version for NDK (default: auto)
        --android_sdk=ANDROID_SDK          The Android SDK Directory
        --build_toolver=BUILD_TOOLVER      The Build Tool Version of Android SDK
        --ndk_stdcxx=[y|n]                 Use stdc++ library for NDK (default: y)
        --ndk_cxxstl=NDK_CXXSTL            The stdc++ stl library for NDK, (deprecated, please use --runtimes)
                                               - c++_static
                                               - c++_shared
                                               - gnustl_static
                                               - gnustl_shared
                                               - stlport_shared
                                               - stlport_static

Command options (Emscripten Configuration):
        --emsdk=EMSDK                      The emsdk directory

Command options (Cuda SDK Configuration):
        --cuda=CUDA                        The Cuda SDK Directory (default: auto)

Command options (Qt SDK Configuration):
        --qt=QT                            The Qt SDK Directory (default: auto)
        --qt_sdkver=QT_SDKVER              The Qt SDK Version (default: auto)

Command options (Vcpkg Configuration):
        --vcpkg=VCPKG                      The Vcpkg Directory (default: auto)

Command options (MingW Configuration):
        --mingw=MINGW                      The MingW SDK Directory

Command options (Other Configuration):
        --debugger=DEBUGGER                Set debugger (default: auto)
        --ccache=[y|n]                     Enable or disable the c/c++ compiler cache. (default: y)
        --ccachedir=CCACHEDIR              Set the ccache directory.
        --trybuild=TRYBUILD                Enable try-build mode and set the third-party buildsystem tool.
                                           e.g.
                                               - xmake f --trybuild=auto; xmake
                                               - xmake f --trybuild=autoconf -p android --ndk=xxx; xmake
                                           
                                           the third-party buildsystems:
                                               - auto
                                               - make
                                               - autoconf
                                               - cmake
                                               - scons
                                               - meson
                                               - bazel
                                               - ninja
                                               - msbuild
                                               - xcodebuild
                                               - ndkbuild
                                               - xrepo
        --tryconfigs=TRYCONFIGS            Set the extra configurations of the third-party buildsystem for the try-build mode.
                                           e.g.
                                               - xmake f --trybuild=autoconf --tryconfigs='--enable-shared=no'
    -o BUILDIR, --buildir=BUILDIR          Set build directory. (default: build)

error: Invalid option: --tensorrt=/usr/local/tensorrt`

**Comment by laugh12321** [comment]
@DefconBird 你看一下根目录是不是有一个`xmake.lua`,使用`xmake f -P . --tensorrt=/usr/local/tensorrt`可以吗？

**Comment by laugh12321** [comment]
@DefconBird 问题已修复，错误原因是 `/plugin/xmake.lua` 缺少一个`,` 导致的错误 `error: ./plugin/xmake.lua:17: ')' expected (to close '(' at line 12) near '"$(projectdir)/plugin/efficientIdxNMSPlugin/*.cpp"` 现已修复。

修复后执行 `xmake f --tensorrt=/usr/local/tensorrt` 会出现一下告警：

```bash
note: the following packages were not found on your system, try again after installing them:
  -> python 3.12.3
```

提示没有找到系统自带的 Python, 执行命令`apt-get update && apt-get install python3-all-dev` 即可解决，`Dockerfile` 稍后会进行更新。

> 使用 xmake 下载所需依赖可能需要开代理，不然很慢。可参考[设置代理](https://xmake.io/#/zh-cn/package/remote_package?id=%e8%ae%be%e7%bd%ae%e4%bb%a3%e7%90%86) 配置。
