### ISSUE TITLE
[Help]: Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.

### ISSUE THREAD

**Issue by SuperJinggg** [laugh12321/TensorRT-YOLO#52]
使用该命令
`trtyolo export -w yolo11s.pt -v ultralytics -o output --max_boxes 100 --iou_thres 0.45 --conf_thres 0.25 -b -1`导出onnx模型时
弹出警告
`[I] Starting export with Pytorch.
[W1104 14:32:43.000000000 shape_type_inference.cpp:1999] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W1104 14:32:43.000000000 shape_type_inference.cpp:1999] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W1104 14:32:43.000000000 shape_type_inference.cpp:1999] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
[W1104 14:32:43.000000000 shape_type_inference.cpp:1999] Warning: The shape inference of TRT::EfficientNMS_TRT type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (function UpdateReliable)
`

**Comment by laugh12321** [comment]
正常现象，是Pytorch C++的警告，Python的warnings 是无法忽略的。导出的ONNX是对的就行

**Comment by SuperJinggg** [comment]
感谢大佬，目前正努力跑通您的代码！！！请问目前我只需要您项目中的c++推理部分，我只需要先编译动态库，然后将lib下的动态库拿出来，然后修改demo中的代码即可吗？

**Comment by laugh12321** [comment]
> 感谢大佬，目前正努力跑通您的代码！！！请问目前我只需要您项目中的c++推理部分，我只需要先编译动态库，然后将lib下的动态库拿出来，然后修改demo中的代码即可吗？

@SuperJinggg 可以参[demo/detect/xmake.lua](https://github.com/laugh12321/TensorRT-YOLO/blob/main/demo%2Fdetect%2Fxmake.lua）的配置。编译动态库后，想要在你自己写的代码里跑通，不仅需要`lib/deploy.so`动态库，还需要`include`头文件，以及CUDA和TensorRT的头文件与动态库。

**Comment by SuperJinggg** [comment]
大佬您好，我遇到了新问题，我将onnx转成engine时报错
`[11/05/2024-10:30:24] [W] Dynamic dimensions required for input: images, but no shapes were provided. Automatically overriding shape to: 1x3x1x1
[11/05/2024-10:30:24] [I] Set shape of input tensor images for optimization profile 0 to: MIN=1x3x1x1 OPT=1x3x1x1 MAX=1x3x1x1
[11/05/2024-10:30:24] [E] Error[4]: IBuilder::buildSerializedNetwork: Error Code 4: API Usage Error (IConcatenationLayer /model.12/Concat: /model.12/Concat: axis 2 dimensions must be equal for concatenation on axis 1. Dimensions are 2 and 1.)
[11/05/2024-10:30:24] [E] Engine could not be created from network
[11/05/2024-10:30:24] [E] Building engine failed
[11/05/2024-10:30:24] [E] Failed to create engine from model or file.
[11/05/2024-10:30:24] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v100600] [b26] # trtexec --onnx=yolo11s_best.onnx --saveEngine=yolo11s_best.engine --fp16`
我搜网上似乎没有解决方案，使用的tensorrtrt版本为10.6，cuda12.5。是否为版本太高导致的？

**Comment by SuperJinggg** [comment]
> 大佬您好，我遇到了新问题，我将onnx转成engine时报错 
`[11/05/2024-10:30:24] [W] Dynamic dimensions required for input: images, but no shapes were provided. Automatically overriding shape to: 1x3x1x1 [11/05/2024-10:30:24] 
[I] Set shape of input tensor images for optimization profile 0 to: MIN=1x3x1x1 OPT=1x3x1x1 MAX=1x3x1x1 [11/05/2024-10:30:24] 
[E] Error[4]: IBuilder::buildSerializedNetwork: Error Code 4: API Usage Error (IConcatenationLayer /model.12/Concat: /model.12/Concat: axis 2 dimensions must be equal for concatenation on axis 1. Dimensions are 2 and 1.) [11/05/2024-10:30:24]
[E] Engine could not be created from network [11/05/2024-10:30:24] 
[E] Building engine failed [11/05/2024-10:30:24] [E] Failed to create engine from model or file. [11/05/2024-10:30:24] 
[E] Engine set up failed &&&& FAILED TensorRT.trtexec [TensorRT v100600] [b26] # trtexec --onnx=yolo11s_best.onnx --saveEngine=yolo11s_best.engine --fp16` 我搜网上似乎没有解决方案，使用的tensorrtrt版本为10.6，cuda12.5。是否为版本太高导致的？
