### ISSUE TITLE
[Help]: ModuleNotFoundError: No module named 'tensorrt_yolo.infer'

### ISSUE THREAD

**Issue by SuperJinggg** [laugh12321/TensorRT-YOLO#53]
我三个方式都报错

1. 使用命令行推理时，报`Usage: trtyolo [OPTIONS] COMMAND [ARGS]...

 Try 'trtyolo --help' for help
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ No such command 'infer'.`

2. 使用python推理时，报` File "D:\projects\my_code\TensorRT-YOLO\demo\detect\detect.py", line 73, in main
    from tensorrt_yolo.infer import CpuTimer, DeployCGDet, DeployDet, GpuTimer, generate_labels_with_colors, visualize_detections
ModuleNotFoundError: No module named 'tensorrt_yolo.infer'`

3.使用c++编译推理时，报`install ffmpeg 7.0 .. failed

Compiler lacks C11 support
If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.`

第一二个方式应该是导包路径没找到，第三个方式我不知道原因，我看了我的git和gcc版本很新`gcc version 14.2.0 (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders, r2)`

**Comment by laugh12321** [comment]
@SuperJinggg 请仔细阅读文档 [快速编译安装](https://github.com/laugh12321/TensorRT-YOLO/blob/main/docs/cn/build_and_install.md) 在 【安装 tensorrt_yolo】部分已经明确说明，如果仅想通过 `tensorrt_yolo` 提供的命令行界面（CLI）工具 `trtyolo`，导出可供该项目推理的 ONNX 模型（带 TensorRT 插件），可以通过 [PyPI](https://pypi.org/project/tensorrt-yolo) 安装。如果想体验与 C++ 同样的推理速度，则需要自行构建最新版本的 `tensorrt_yolo`。

- 你第一个问题的报错 `ModuleNotFoundError: No module named 'tensorrt_yolo.infer'` 就是因为没有根据文档进行构建最新版本的 `tensorrt_yolo`，而选择下载 [PyPI](https://pypi.org/project/tensorrt-yolo) 的包，PYPI的包仅包含导出功能，不包含推理功能。因为需要根据设备的CUDA和TensorRT进行编译。

- 第二个问题的 `install ffmpeg 7.0 .. failed` 是因为你使用 xmake 进行编译设置时，它会安装需要的依赖。但是由于网络问题导致下载失败，使用 xmake 下载所需依赖可能需要开代理，不然很慢。可参考 Xmake 的官方文档 [设置代理](https://xmake.io/#/zh-cn/package/remote_package?id=%e8%ae%be%e7%bd%ae%e4%bb%a3%e7%90%86) 配置。

**Comment by laugh12321** [comment]
@SuperJinggg 出现 `RuntimeError: Dynamic dimensions not supported.` 错误是[因为推理动态引擎时使用 CUDA Graph 加速](https://github.com/laugh12321/TensorRT-YOLO/blob/main/source/deploy/vision/detection.cpp#L341)， 而 CUDA Graph 加速只支持静态引擎。这在[文档](https://github.com/laugh12321/TensorRT-YOLO/blob/main/demo/detect/README.md#%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86)中已经高亮提示了，请认真阅读文档，如下图。

![image](https://github.com/user-attachments/assets/4d0663fe-66b0-4a0f-8f7f-5b9b4a4318e6)

出现 `Failed to build onnxsim` 错误则是，在 Windows 下使用 pip 安装 `onnxsim` 的通病，使用 `conda` 安装即可。`onnxsim` 库数据模型导出时锦上添花的功能，可以不使用。

如果你只想用C++部分的推理，文档中的Python相关教程可忽略，仅通过 [PyPI](https://pypi.org/project/tensorrt-yolo) 安装用以导出模型。实际构建的`whl`包，在安装时加上`[export]`会下载用于模型导出的依赖库。你也可以直接运行 `pip install dist/tensorrt_yolo-4.*-py3-none-any.whl` 在导出模型时，缺少那个依赖再安装哪个。
