### ISSUE TITLE
[Help]: 新版本如何编译使用

### ISSUE THREAD

**Issue by AJgz966** [laugh12321/TensorRT-YOLO#57]
新版的 编译trt  是要把几个文件都放进去吗，我看之前的教程就一个插件  ，然后编译好了 调用的接口可以出个教程吗 小白不太懂  麻烦大佬了

**Comment by laugh12321** [comment]
@AJgz966 没有问题这个issue将会被关闭。

**Comment by AJgz966** [comment]
现在已经编译成功并且运行了 辛苦了&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月15日(星期五) 晚上7:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [laugh12321/TensorRT-YOLO] [Help]: 新版本如何编译使用 (Issue #57)














 
@AJgz966 没有问题这个issue将会被关闭。
