### ISSUE TITLE
[Feature]: 支持yolo-pose

### ISSUE THREAD

**Issue by zoulee24** [laugh12321/TensorRT-YOLO#58]
项目需要写了一个yolo11的EfficientPoseNMSPlugin，可以申请合并吗，目前只测试了linux环境的TensorRT，没有看到讨论区所以提了一个issue，可以的话我整理一下提一个pull requests？

**Comment by laugh12321** [comment]
@zoulee24 非常感谢你对项目的贡献和对开源社区的热情。

目前，YOLO-Pose 和 YOLO-Segment 计划使用[efficientIdxNMSPlugin](https://github.com/laugh12321/TensorRT-YOLO/tree/main/plugin/efficientIdxNMSPlugin) 插件目前来加速推理。目前的推理部分代码还在开发阶段，可以发你一下 使用 `efficientIdxNMSPlugin` 导出的 `yolo11n-pose` 的ONNX 模型，看看是否与使用你实现的 `EfficientPoseNMSPlugin` 导出的 ONNX 输出是否一致，如果一致在未来可以无缝的使用项目的推理模块来进行加速。 

![image](https://github.com/user-attachments/assets/b30158e6-a921-45c7-8c6e-deaf1e283692)

**Comment by zoulee24** [comment]
确认我们的输出是一致的，后续我将会测试动态推理能否正常运行，完善后看看能否与项目达一致。

[`yolo11m-pose-with-EfficientPoseNMSPlugin`](https://www.ilanzou.com/s/rdZyQz2N)


我在测试c++动态导入这个链接库的时候，遇到一个奇怪的问题，不知道您有没有遇到类似问题。
```cpp
int main()
{
    // 动态加载额外插件库
    auto plugin_handle = dlopen("/code/csentinelnode/build/libtrt_nms_extra_plugins.so", RTLD_LAZY);
    // void *const plugin_handle = runtime->getPluginRegistry().loadLibrary(custom_plugin.c_str());
    if (plugin_handle == nullptr)
    {
        throw std::runtime_error("无法找到库");
    }
    dlclose(plugin_handle);
    return EXIT_SUCCESS;
}
```
在关闭ddl后会发生指针释放错误`free(): invalid pointer`，
不管是使用`runtime->getPluginRegistry().loadLibrary("plugin_path")`
还是`dlopen("plugin_path")`都会发生同样的错误。

我没有采用[插件包含在引擎中](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#generating-plugin-library)的做法，每次加载engine时载入自定义插件库。

调试结果显示是nvinfer的`LogStream`析构出现问题，是我的使用问题吗？
![image](https://github.com/user-attachments/assets/79aa01c9-8986-4977-bcbb-5bae082b93c4)

**Comment by laugh12321** [comment]
@zoulee24 `free(): invalid pointer` 有可能是释放已经被释放的指针。我之前遇到过类似的问题，原因是实现的析构中，指针释放的先后顺序不对。

**Comment by zoulee24** [comment]
@laugh12321 已经解决了这个问题，问题定位到[四个日志记录全局变量](https://github.com/laugh12321/TensorRT-YOLO/blob/main/plugin/common/checkMacrosPlugin.cpp#L52C1-L55C52)，由于没有显示释放无法更加详细定位到其他地方。

另外还有一个**bug**是在TensorRT>10.x版本下，定义公共符号问题[line41-line45](https://github.com/laugh12321/TensorRT-YOLO/blob/main/plugin/common/vfcCommon.h#L41C1-L45C7)，[相关文档](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#generating-plugin-library)，函数名应该是`getPluginCreators`保持不变。

我的解决方案是使用`getLogger`函数去除定义全局变量用做日志记录，我认为插件初始化`initLibNvInferPlugins`时是会传入日志指针进来，可以利用用户自定义的`ILogger`或者`nullptr`不输出日志。

**Comment by laugh12321** [comment]
@zoulee24 没有理解你说的这个问题，在TensorRT 10.x 以后的版本都是使用的 `getCreators` 之前的则是使用 `getPluginCreators`。 你发的10.x文档的它也是这么说的。

![image](https://github.com/user-attachments/assets/71cea08a-4f50-45d1-84a9-908d487e11b2)

你也可以看一下 TensorRT 的源码，从10.x 开始 `getPluginCreators` 就被弃用了。

**Comment by zoulee24** [comment]
@laugh12321 动态链接库使用的时候导入这个库会报内部错误，版本为`10.0.x`：
`[libLoader.cpp::untypedSymbolAddress::363] Error Code 3: Internal Error (SymbolAddress for getPluginCreators could not be loaded, check function name against library symbol)`

建议多一个版本判断，TensorRT>10.0.x,<10.1.x情况下需要按照以下多导出一个符号，要不然会报内部错误缺少公共符号`getPluginCreators`。
[官方示例代码](https://github.com/NVIDIA/TensorRT/blob/release/10.0/plugin/common/vfcCommon.h)

**Comment by laugh12321** [comment]
@zoulee24 等我回头试试，我记得10.0.x 是可以直接使用 `getCreators` 的。

**Comment by laugh12321** [comment]
@zoulee24 确实有这个问题，已经重新开了一个issue https://github.com/laugh12321/TensorRT-YOLO/issues/59
