### ISSUE TITLE
[Bug]: 最新的5.0版本最后使用cmake编译会出现LINK : fatal error LNK1181: 无法打开输入文件“deploy.lib”

### ISSUE THREAD

**Issue by cxcxxx** [laugh12321/TensorRT-YOLO#62]
### 问题描述 Please describe your issue

执行最后的cmake --build . -j8 --config Release命令后报错LINK : fatal error LNK1181: 无法打开输入文件“deploy.lib” [C:\Users\source\repos\TensorRT-YOLO-5.0.0\examples\detect\build\detect.vcxproj]同时打开sln文件也是同样的问题，重新试了很多次都是这个问题不清楚是不是个人环境问题

**Comment by laugh12321** [comment]
@cxcxxx 这是一个bug, 使用cmake编译后，动态库路径和生成对应的.lib辅助库文件不在同一个路径下。马上修复，你也可以在build文件夹中找到，并移动到lib文件夹。

**Comment by cxcxxx** [comment]
> @cxcxxx 这是一个bug, 使用cmake编译后，动态库路径和生成对应的.lib辅助库文件不在同一个路径下。马上修复，你也可以在build文件夹中找到，并移动到lib文件夹。

非常感谢大佬的为爱发电，我也有尝试寻找这个lib但是并没有在电脑中找到，我是通过everything搜索这个lib文件发现没有找到

**Comment by laugh12321** [comment]
@cxcxxx 你下拉一下代码，已经修复了。

**Comment by cxcxxx** [comment]
> @cxcxxx 你下拉一下代码，已经修复了。
太太太感谢大佬成功编译并且运行了！
![QQ20241123-120707](https://github.com/user-attachments/assets/383a0bce-2a7d-4c5b-8735-4d9d72ff0dd7)
