### ISSUE TITLE
[Help]: TensorRT-YOLO 的 Deploy 模块集成到 VideoPipe 中进行视频分析，执行./PipeDemo 中断

### ISSUE THREAD

**Issue by 417452105** [laugh12321/TensorRT-YOLO#63]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

TensorRT-YOLO 的 Deploy 模块集成到 VideoPipe 中进行视频分析，xmake编译生成了PipeDemo，但是执行不了，环境配置是cuda11.8，cudnn8.9，TensorRT8.6.1.6，opencv4.7。不知道问题在哪里，麻烦大佬指点。
![image](https://github.com/user-attachments/assets/39a6e9c4-51de-4540-8ce7-2720c5cfc841)

**Comment by 417452105** [comment]
detect示例可以正常推理，VideoPipe不可以

**Comment by laugh12321** [comment]
@417452105 这是VideoPipe的问题，请在VideoPipe的仓库下提问。具体原因可能是xmake编译引起的，使用cmake编译正常。结局方案是注释 https://github.com/sherlockchou86/VideoPipe/blob/master/utils/logger/vp_logger.cpp#L44C1-L46C10 这段代码后重新编译 VideoPipe.
