### ISSUE TITLE
[Help]: more than one conversion function from "__half" to a built-in type applies

### ISSUE THREAD

**Issue by whuhit** [laugh12321/TensorRT-YOLO#66]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我没有使用CMake和XMake，而是直接手动在visual studio2022中添加源码，设置cuda编译器，然后进行编译，现在的问题是编译报错 more than one conversion function from "__half" to a built-in type applies，如下图，这个有遇到过吗，如何解决
![image](https://github.com/user-attachments/assets/a55f2a67-ca79-4650-86dc-6a898a0171fc)

**Comment by laugh12321** [comment]
@whuhit 应该是版本不匹配的原因，你的TensorRT版本与CUDA版本不对应。

如果你想使用 [Efficient Rotated NMS Plugin](https://github.com/laugh12321/TensorRT-YOLO/tree/eb018e770a67f3cbc0c50e0101f80cbeb683024e/plugin/efficientRotatedNMSPlugin) 与 [Efficient NMS Plugin With Indices](https://github.com/laugh12321/TensorRT-YOLO/tree/eb018e770a67f3cbc0c50e0101f80cbeb683024e/plugin/efficientIdxNMSPlugin) 插件，建议在Linux上使用，Windows下的TensorRT trtexec构建引擎时存在BUG，目前正在联系官方解决 https://github.com/NVIDIA/TensorRT/issues/4274 。

**Comment by whuhit** [comment]
嗯嗯好的，刚才查到一些解决方法，设置cuda编译参数，将--arch从compute_52,sm_52改成compute_70,sm_70后，现在编译通过了，后续运行过程中还有问题的话，我再转linux下试用

**Comment by laugh12321** [comment]
@whuhit 好的👌🏻，这个问题解决了的话，那么issue将关闭了。

**Comment by whuhit** [comment]
好的，刚才用了下，运行推理结果也是正常的，非常感谢，很棒的代码！

**Comment by laugh12321** [comment]
@whuhit 感谢认可😁

**Comment by whuhit** [comment]
> @whuhit 应该是版本不匹配的原因，你的TensorRT版本与CUDA版本不对应。
> 
> 如果你想使用 [Efficient Rotated NMS Plugin](https://github.com/laugh12321/TensorRT-YOLO/tree/eb018e770a67f3cbc0c50e0101f80cbeb683024e/plugin/efficientRotatedNMSPlugin) 与 [Efficient NMS Plugin With Indices](https://github.com/laugh12321/TensorRT-YOLO/tree/eb018e770a67f3cbc0c50e0101f80cbeb683024e/plugin/efficientIdxNMSPlugin) 插件，建议在Linux上使用，Windows下的TensorRT trtexec构建引擎时存在BUG，目前正在联系官方解决 [NVIDIA/TensorRT#4274](https://github.com/NVIDIA/TensorRT/issues/4274) 。
> 
> 如果你不使用 [Efficient Rotated NMS Plugin](https://github.com/laugh12321/TensorRT-YOLO/tree/eb018e770a67f3cbc0c50e0101f80cbeb683024e/plugin/efficientRotatedNMSPlugin) 与 [Efficient NMS Plugin With Indices](https://github.com/laugh12321/TensorRT-YOLO/tree/eb018e770a67f3cbc0c50e0101f80cbeb683024e/plugin/efficientIdxNMSPlugin) 插件，可以在将以下这行注释掉，就不会编译自定义插件。
> 
> https://github.com/laugh12321/TensorRT-YOLO/blob/eb018e770a67f3cbc0c50e0101f80cbeb683024e/CMakeLists.txt#L75


![image](https://github.com/user-attachments/assets/349f8062-0d1c-40c7-9e4a-96bb38e7e831)

使用trtexec.exe去将带插件的onnx生成引擎文件我在Windows下确实一直报错，但是我今天试了下，将EfficientIdxNMSPlugin和EfficientRotatedNMSPlugin注册一下，然后用tensorrt官方的引擎文件生成代码，是可以生成引擎文件的，而且也可以正常加载和推理。

**Comment by laugh12321** [comment]
你注册到哪里了？源码编译TensorRT吗？

**Comment by whuhit** [comment]
> @whuhit 是直接使用TensorRT API构建引擎？不使用trtexec吗？

对的，但是我的结果感觉有一点点问题。我感觉rotatednms没生效还是咋的，我有一张图，检测结果是这样的
![image](https://github.com/user-attachments/assets/9f735a15-a16b-4857-a153-afb37c45f202)
 后面的这些结果应该是要被nms过滤掉的，但是实际上没有。我用的图是下面这张

![P0073_640](https://github.com/user-attachments/assets/5818da62-23a8-479f-8692-a2d8d6016257)

**Comment by laugh12321** [comment]
@whuhit 会有这个问题，有的目标会有好几个框。这个是算子精度的问题，会导致出现这个问题。

**Comment by whuhit** [comment]
> @whuhit 会有这个问题，有的目标会有好几个框。这个是算子精度的问题，会导致出现这个问题。

这不是精度问题吧，后面6个框，看坐标和角度是差不多的，应该就是重叠的太多了，rotated nms应该就是来过滤这个的吧，过滤完了，剩两个结果才对。我用python代码推理这张图的话是两个结果，你能帮忙用C++推理下上面那张图吗😂，看下结果跟我那个是不是一样的

**Comment by laugh12321** [comment]
@whuhit 我是说是我写的插件的精度问题，我测试过的。对于有些图像会有重复框没有被过滤的情况。

**Comment by whuhit** [comment]
> @whuhit 我是说是我写的插件的精度问题，我测试过的。对于有些图像会有重复框没有被过滤的情况。你可以跑一下example/obb 的C++和Python示例。

刚试了下fp32的engine，推理结果确实只有两个🤣这可太奇怪了，这个精度问题算bug吗，是不是可以修复一下

**Comment by laugh12321** [comment]
@whuhit 我也想修复，但是问题不在我这里，除非强制引擎以fp16构建时也用fp32精度。

**Comment by whuhit** [comment]
> @whuhit 我也想修复，但是问题不在我这里，除非强制引擎以fp16构建时插件也用fp32精度。你可以看一下插件的源码。

嗯好的好的，我看一下

**Comment by laugh12321** [comment]
@whuhit 看`.cuh`和`.cu`文件就可以，在`.cuh`文件开头定义了HALF和FLOAT是一些运算操作的对应实现。然后在`.cu`最后根据不同的类型选择对应的实现计算。

**Comment by whuhit** [comment]
> @whuhit 看`.cuh`和`.cu`文件就可以，在`.cuh`文件开头定义了HALF和FLOAT的一些运算操作的对应实现。然后在`.cu`最后根据不同的类型选择对应的实现计算。

大神方便留个联系方式吗，还有几个问题请教一下😁或者你加我微信，我的微信号whuhit

**Comment by laugh12321** [comment]
> > @whuhit 是直接使用TensorRT API构建引擎？不使用trtexec吗？
> 
> 对的，但是我的结果感觉有一点点问题。我感觉rotatednms没生效还是咋的，我有一张图，检测结果是这样的 ![image](https://private-user-images.githubusercontent.com/22534064/395101950-9f735a15-a16b-4857-a153-afb37c45f202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODUyNDksIm5iZiI6MTczNDQ4NDk0OSwicGF0aCI6Ii8yMjUzNDA2NC8zOTUxMDE5NTAtOWY3MzVhMTUtYTE2Yi00ODU3LWExNTMtYWZiMzdjNDVmMjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAxMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlN2M1OTFjODQyMjNjZjlmNjYzZjE2Y2IzNzY4YzIxODAyOTQyNWI4MjUyYWQyZDRkYmIwMjY4MmFmMmQ3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GC1EV4-Dg407l7idl-vTeIOm2pnS3Y0JdYSFfc-qAtM) 后面的这些结果应该是要被nms过滤掉的，但是实际上没有。我用的图是下面这张
> 
> ![P0073_640](https://private-user-images.githubusercontent.com/22534064/395102300-5818da62-23a8-479f-8692-a2d8d6016257.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODUyNDksIm5iZiI6MTczNDQ4NDk0OSwicGF0aCI6Ii8yMjUzNDA2NC8zOTUxMDIzMDAtNTgxOGRhNjItMjNhOC00NzlmLTg2OTItYTJkOGQ2MDE2MjU3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDAxMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ODI4NzUyZjg0OWU2YzFkNTRlODA4NGI2YTAzYjU0ZDUwNzI5Y2U1NWZkY2VjN2E0OTM4MGFiOGQxMTllMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MLhe7FelowolJJCiNi1MSMIt0EKHsBf0Ul7cIqCjnmE)

上述问题已经重新开了一个issue https://github.com/laugh12321/TensorRT-YOLO/issues/71

**Comment by laugh12321** [comment]
@whuhit RotatedNMS 插件精度问题已修复，详见 https://github.com/laugh12321/TensorRT-YOLO/pull/72
