### ISSUE TITLE
[Doc]: pip install dist/tensorrt_yolo-5.*-py3-none-any.whl[export] needs single quote

### ISSUE THREAD

**Issue by Liu-Hong-Xin-1219** [laugh12321/TensorRT-YOLO#67]
### 文档链接&描述 Document Links & Description

**bugged doc**: [快速编译安装](https://github.com/laugh12321/TensorRT-YOLO/blob/main/docs/cn/build_and_install.md)
**bug**: do `pip install dist/tensorrt_yolo-5.*-py3-none-any.whl[export]` 
         will report error `Could not install packages due to an OSError: [Errno 2] No such file or directory:...`

### 请提出你的建议 Please give your suggestion

add single quote:
` pip install 'dist/tensorrt_yolo-5.*-py3-none-any.whl[export]'`

**Comment by laugh12321** [comment]
@Liu-Hong-Xin-1219  指令中的 `dist/tensorrt_yolo-5.*-py3-none-any.whl[export]` 只是一个示例，`*` 要根据实际生成的版本填写，目前的大多数终端打出dist时按住tab就会自动填写完整的文件名。

**Comment by Liu-Hong-Xin-1219** [comment]
我的意思是，如果加了[export]，那么`dist/tensorrt_yolo-5.*-py3-none-any.whl[export]`部分需要加单引号, 否则会报错.
