### ISSUE TITLE
[Help]: 批处理异常 修改model->batch后报错

### ISSUE THREAD

**Issue by Liu-Hong-Xin-1219** [laugh12321/TensorRT-YOLO#68]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我将模型设置为动态，当我尝试在segment.cpp之中，修改model->batch=2再运行，会交替出现两种错误：
CUDA Error:
    File:     path-to-project/source/deploy/core/tensor.cpp
    Line:       18
    Error code: 1
    Error text: invalid argument
Segmentation fault (core dumped)
和
CUDA Error:
    File:        path-to-project/source/deploy/vision/inference.cpp
    Line:       275
    Error code: 400
    Error text: invalid resource handle
Segmentation fault (core dumped)
line 275 是 CUDA(cudaMemcpyAsync(imageDevice, imageHost, imageSize * sizeof(uint8_t), cudaMemcpyHostToDevice, stream));
请问为什么？如何解决？

环境：ubuntu20.04 
操作步骤
#编译
cmake -DTENSORRT_PATH=/root/TensorRT-8.6.1.6 ..
#pt转onnx
trtyolo export -w weight/yolov8n-seg.pt -v ultralytics -o weight -b -1
#onnx转engine 动态
trtexec --onnx=weight/yolov8n-seg.onnx --saveEngine=weight/yolov8n-seg.engine --minShapes=images:1x3x640x640 --optShapes=images:4x3x640x640 --maxShapes=images:8x3x640x640 --fp16 --dynamicPlugins=/root/autodl-tmp/mytrtyolo/lib/plugin/libcustom_plugins.so --setPluginsToSerialize=/root/autodl-tmp/mytrtyolo/lib/plugin/libcustom_plugins.so
#验证
trtexec --fp16 --avgRuns=1000 --useSpinWait --loadEngine=weight/yolov8n-seg.engine
  
#使用 cmake 编译
mkdir -p build && cd build
cmake -DTENSORRT_PATH="/root/TensorRT-8.6.1.6" -DDEPLOY_PATH="/root/autodl-tmp/mytrtyolo" ..
cmake --build . -j8 --config Release
#运行
./segment -e /root/autodl-tmp/mytrtyolo/weight/yolov8n-seg.engine -i /root/autodl-tmp/mytrtyolo/data_zoo/cocopart -o /root/autodl-tmp/mytrtyolo/oout -l ../labels.txt

**Comment by laugh12321** [comment]
@Liu-Hong-Xin-1219 

首先，无论模型是动态还是静态，`batch` 都不需要你手动设置。它是自己解析的（参见代码 [DeployTemplate<T>::setupTensors()](https://github.com/laugh12321/TensorRT-YOLO/blob/main/source/deploy/vision/inference.cpp#L233)）。

其次，在解析时如果为动态模型，则将`batch`设置为你构建引擎时的最大批次。这样做的目的是在运行 [`std::vector<T> DeployTemplate<T>::predict(const std::vector<Image>& images)`](https://github.com/laugh12321/TensorRT-YOLO/blob/main/source/deploy/vision/inference.cpp#L296) 时接收的`images`长度都不大于所设定的`bacth`。

**Comment by Liu-Hong-Xin-1219** [comment]
谢谢笑哥(●'◡'●)
