### ISSUE TITLE
[help] 希望帮忙解决TensorRT-YOLO 编译失败

### ISSUE THREAD

**Issue by twd123-a** [laugh12321/TensorRT-YOLO#75]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

(cuda111) jy@jy-desktop:~/twd/yolov11_infer/TensorRT-YOLO/build$ cmake -DTENSORRT_PATH=/usr/local/tensorrt ..
CMake Error at CMakeLists.txt:4 (cmake_policy):
  Policy "CMP0146" is not known to this version of CMake.

-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 11.1.105
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda-11.1/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-11.1/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda-11.1 (found version "11.1")
-- Found Python: /home/jy/miniconda3/envs/cuda111/bin/python3.8 (found version "3.8.20") found components: Interpreter Development
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /home/jy/miniconda3/envs/cuda111/include (found version "2.13.6")
-- Configuring incomplete, errors occurred!
See also "/home/jy/twd/yolov11_infer/TensorRT-YOLO/build/CMakeFiles/CMakeOutput.log".
See also "/home/jy/twd/yolov11_infer/TensorRT-YOLO/build/CMakeFiles/CMakeError.log".

**Comment by laugh12321** [comment]
@twd123-a 将 `CMakeLists.txt` 中的第四行`cmake_policy(SET CMP0146 OLD)`注释了试试

**Comment by twd123-a** [comment]
已经试过了，-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed还是存在

**Comment by laugh12321** [comment]
@twd123-a 是不是你的环境没有 pthread

**Comment by twd123-a** [comment]
> @twd123-a 将 `CMakeLists.txt` 中的第四行`cmake_policy(SET CMP0146 OLD)`注释了试试

**Comment by laugh12321** [comment]
@twd123-a 解决了吗？

**Comment by twd123-a** [comment]
> @twd123-a 是不是你的环境没有 pthread

可以查看pthread并且pthread已经写入环境变量，

**Comment by laugh12321** [comment]
@twd123-a 可以看看这个链接 https://stackoverflow.com/questions/64514666/what-does-performing-test-cmake-have-libc-pthread-failed-actually-mean

**Comment by twd123-a** [comment]
> @twd123-a 解决了吗？
没有

**Comment by twd123-a** [comment]
> @twd123-a 可以看看这个链接 https://stackoverflow.com/questions/64514666/what-does-performing-test-cmake-have-libc-pthread-failed-actually-mean

我觉得我的编译失败原因不在于上面的pthread failed,而是在See also "/home/jy/twd/yolov11_infer/TensorRT-YOLO/build/CMakeFiles/CMakeError.log".中。
Performing C++ SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/jy/twd/yolov11_infer/TensorRT-YOLO/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_b4bb2/fast && /usr/bin/make  -f CMakeFiles/cmTC_b4bb2.dir/build.make CMakeFiles/cmTC_b4bb2.dir/build
make[1]: 进入目录“/home/jy/twd/yolov11_infer/TensorRT-YOLO/build/CMakeFiles/CMakeTmp”
Building CXX object CMakeFiles/cmTC_b4bb2.dir/src.cxx.o
/usr/bin/c++    -DCMAKE_HAVE_LIBC_PTHREAD   -std=gnu++1z -o CMakeFiles/cmTC_b4bb2.dir/src.cxx.o -c /home/jy/twd/yolov11_infer/TensorRT-YOLO/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_b4bb2
/usr/bin/cmake-3.16.8-Linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b4bb2.dir/link.txt --verbose=1
/usr/bin/c++   -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_b4bb2.dir/src.cxx.o  -o cmTC_b4bb2 
CMakeFiles/cmTC_b4bb2.dir/src.cxx.o：在函数‘main’中：
src.cxx:(.text+0x3e)：对‘pthread_create’未定义的引用
src.cxx:(.text+0x4a)：对‘pthread_detach’未定义的引用
src.cxx:(.text+0x5b)：对‘pthread_join’未定义的引用
src.cxx:(.text+0x6f)：对‘pthread_atfork’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_b4bb2.dir/build.make:89: recipe for target 'cmTC_b4bb2' failed
make[1]: *** [cmTC_b4bb2] Error 1
make[1]: 离开目录“/home/jy/twd/yolov11_infer/TensorRT-YOLO/build/CMakeFiles/CMakeTmp”
Makefile:124: recipe for target 'cmTC_b4bb2/fast' failed
make: *** [cmTC_b4bb2/fast] Error 2


Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/jy/twd/yolov11_infer/TensorRT-YOLO/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_b4b0d/fast && /usr/bin/make  -f CMakeFiles/cmTC_b4b0d.dir/build.make CMakeFiles/cmTC_b4b0d.dir/build
make[1]: 进入目录“/home/jy/twd/yolov11_infer/TensorRT-YOLO/build/CMakeFiles/CMakeTmp”
Building CXX object CMakeFiles/cmTC_b4b0d.dir/CheckFunctionExists.cxx.o
/usr/bin/c++    -DCHECK_FUNCTION_EXISTS=pthread_create   -std=gnu++1z -o CMakeFiles/cmTC_b4b0d.dir/CheckFunctionExists.cxx.o -c /home/jy/twd/yolov11_infer/TensorRT-YOLO/build/CMakeFiles/CheckLibraryExists/CheckFunctionExists.cxx
Linking CXX executable cmTC_b4b0d
/usr/bin/cmake-3.16.8-Linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b4b0d.dir/link.txt --verbose=1
/usr/bin/c++   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_b4b0d.dir/CheckFunctionExists.cxx.o  -o cmTC_b4b0d  -lpthreads 
/usr/bin/ld: 找不到 -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_b4b0d.dir/build.make:89: recipe for target 'cmTC_b4b0d' failed
make[1]: *** [cmTC_b4b0d] Error 1
make[1]: 离开目录“/home/jy/twd/yolov11_infer/TensorRT-YOLO/build/CMakeFiles/CMakeTmp”
Makefile:124: recipe for target 'cmTC_b4b0d/fast' failed
make: *** [cmTC_b4b0d/fast] Error 2

**Comment by laugh12321** [comment]
@twd123-a 从错误日志中看，问题不就是找不到`pthread`吗？

**Comment by laugh12321** [comment]
@twd123-a 现在解决了吗？

**Comment by twd123-a** [comment]
> @twd123-a 现在解决了吗？
第一个问题解决了cmake --build . -j8 --config Release编译一直报/usr/bin/ld: 找不到 -lnvinfer
/usr/bin/ld: 找不到 -lnvinfer_plugin
/usr/bin/ld: 找不到 -lnvonnxparser
可是这三个so文件在我的/usr/local/TensorRT-8.6.1.6/targets/x86_64-linux-gnu/lib/目录下，并且写入了环境变量。

**Comment by laugh12321** [comment]
@twd123-a 那这都是一个问题，你没有正确配置环境变量。你要把执行文件配置到`PATH`，动态库配置到`LD_LIBRARY_PATH`

```
echo 'export PATH=/usr/local/cuda-12.5/bin:/usr/local/tensorrt/bin:/usr/local/cmake/bin:$PATH' >> ~/.bashrc
echo 'export LD_LIBRARY_PATH=/usr/local/cuda-12.5/lib64:/usr/local/tensorrt/lib:$LD_LIBRARY_PATH' >> ~/.bashrc
source ~/.bashrc
```

**Comment by twd123-a** [comment]
> /usr/local/TensorRT-8.6.1.6/targets/x86_64-linux-gnu/lib/

添加 echo 'export LIBRARY_PATH=/usr/local/TensorRT-8.6.1.6/lib/:$LIBRARY_PATH' >> ~/.bashrc解决了，又有新的报错

**Comment by twd123-a** [comment]
> > /usr/local/TensorRT-8.6.1.6/targets/x86_64-linux-gnu/lib/
> 
> 添加 echo 'export LIBRARY_PATH=/usr/local/TensorRT-8.6.1.6/lib/:$LIBRARY_PATH' >> ~/.bashrc解决了，又有新的报错
[ 95%] Linking CXX shared module ../tensorrt_yolo/libs/pydeploy.cpython-38-x86_64-linux-gnu.so
CMakeFiles/Makefile2:154: recipe for target 'plugin/CMakeFiles/custom_plugins.dir/all' failed
make[1]: *** [plugin/CMakeFiles/custom_plugins.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 95%] Built target pydeploy
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by laugh12321** [comment]
@twd123-a 这些不属于这个项目的问题你可以自定百度一下。你清理构建目录，重新编译就好了。

**Comment by twd123-a** [comment]
> @twd123-a 这些不属于这个项目的问题你可以自定百度一下。你清理构建目录，重新编译就好了。
> 
> ```
> rm -rf build/
> mkdir build && cd build  # 创建并进入构建目录
> cmake -DTENSORRT_PATH=/usr/local/tensorrt ..  # 配置TensorRT路径
> cmake --build . -j8 --config Release  # 编译项目，使用8个核心
> ```
我每次编译失败之后都会删除新构建的，然后重新编译，确实存在错误。
/home/jy/twd/yolov11_infer/TensorRT-YOLO/plugin/efficientRotatedNMSPlugin/efficientRotatedNMSInference.cu(659): here

4 errors detected in the compilation of "/home/jy/twd/yolov11_infer/TensorRT-YOLO/plugin/efficientRotatedNMSPlugin/efficientRotatedNMSInference.cu".
plugin/CMakeFiles/custom_plugins.dir/build.make:143: recipe for target 'plugin/CMakeFiles/custom_plugins.dir/efficientRotatedNMSPlugin/efficientRotatedNMSInference.cu.o' failed
make[2]: *** [plugin/CMakeFiles/custom_plugins.dir/efficientRotatedNMSPlugin/efficientRotatedNMSInference.cu.o] Error 1
make[2]: *** 正在等待未完成的任务....

**Comment by laugh12321** [comment]
@twd123-a 你发一下完整的终端编译日志，你发的上面没有看到错误在哪。

**Comment by twd123-a** [comment]
[build.log](https://github.com/user-attachments/files/18205176/build.log)

**Comment by laugh12321** [comment]
@whuhit 与 #66 是同样的问题，以下是两种解决办法。

- https://github.com/laugh12321/TensorRT-YOLO/issues/66#issuecomment-2533550498
- https://github.com/laugh12321/TensorRT-YOLO/issues/66#issuecomment-2533669434

**Comment by twd123-a** [comment]
> @whuhit 与 #66 是同样的问题，以下是两种解决办法。核心原因是CUDA版本和TensorRT版本不匹配导致的。
> 
> * [[Help]: more than one conversion function from "__half" to a built-in type applies #66 (comment)](https://github.com/laugh12321/TensorRT-YOLO/issues/66#issuecomment-2533550498)
> * [[Help]: more than one conversion function from "__half" to a built-in type applies #66 (comment)](https://github.com/laugh12321/TensorRT-YOLO/issues/66#issuecomment-2533669434) （需在 [NVIDIA CUDA GPUs](https://developer.nvidia.com/cuda-gpus) 查看你 GPU 的 Compute Capability， 然后将CMakeLists 中的 `set(CMAKE_CUDA_ARCHITECTURES native)` 修改为你查到数值比如 `8.9` `set(CMAKE_CUDA_ARCHITECTURES 89)`）

我还在linux上开发，如果不要这个插件会有什么影响吗？

**Comment by laugh12321** [comment]
@twd123-a 
- 首先，Windows上的Bug 已经修复。
- 其次，如果你只用于 Detect 和 Classify 任务，那么就不需要编译插件，这些插件是用于 OBB、 Pose 和 Segment 任务的。
- 出现 `error: more than one conversion function from “__half“ to a built-in type applies` 错误的核心原因是CUDA版本和TensorRT版本不匹配导致的。第二个已经给出了解决方法，出处自：https://blog.csdn.net/XCCCCZ/article/details/144533487

**Comment by twd123-a** [comment]
> @twd123-a
> 
> * 首先，Windows上的Bug 已经修复。
> * 其次，如果你只用于 Detect 和 Classify 任务，那么就不需要编译插件，这些插件是用于 OBB、 Pose 和 Segment 任务的。
> * 出现 `error: more than one conversion function from “__half“ to a built-in type applies` 错误的核心原因是CUDA版本和TensorRT版本不匹配导致的。上面回答的第二个链接已经给出了解决方法，出处自：https://blog.csdn.net/XCCCCZ/article/details/144533487

好的 谢谢，我理解的是必须编译之后生成相应的python绑定才能用python sdk对吧，

**Comment by laugh12321** [comment]
@twd123-a 是的，必须先编译生成相应的绑定才能使用Python SDK。不过绑定和插件没有关系，插件只是为了构建引擎是集成后处理（这样比推理完再使用CPU或GPU实现后处理要快）。

**Comment by twd123-a** [comment]
> @twd123-a 是的，必须先编译生成相应的绑定才能使用Python SDK。不过绑定和插件没有关系，插件只是为了构建引擎时集成后处理（这样比推理完再使用CPU或GPU实现后处理要快）。
你的python推理示例中的模型，是否支持ultralytics官方提供的pt->onnx->engine模型

**Comment by laugh12321** [comment]
@twd123-a 没有明白你的意思，在[模型支持列表](https://github.com/laugh12321/TensorRT-YOLO?tab=readme-ov-file#support-models) 已经列出了所支持的模型。不过它们都需要导出为该项目支持的ONNX（比如加了插件）再构建为引擎。

**Comment by twd123-a** [comment]
> @twd123-a 没有明白你的意思，在[模型支持列表](https://github.com/laugh12321/TensorRT-YOLO?tab=readme-ov-file#support-models) 已经列出了所支持的模型。不过它们都需要导出为该项目支持的ONNX（比如加了插件）再构建为引擎。不能直接使用 Ultralytics官方直接导出的 onnx 或 engine 推理（因为慢，上面已经解释了）。
sorry ,就是我使用了ultralytics官方提供的方法将pt->onnx使用trtexec工具直接将onnx->engine模型，运行推理时候发生断错误（核心已转储）

**Comment by laugh12321** [comment]
@twd123-a 这样是不支持的，README也写的很清楚。

![image](https://github.com/user-attachments/assets/4b140504-ce66-42f6-9fd1-1430aa15a391)

具体的使用示例请查看 [examples](https://github.com/laugh12321/TensorRT-YOLO/tree/main/examples)

**Comment by twd123-a** [comment]
> @twd123-a 这样是不支持的，README也写的很清楚。
> 
> ![image](https://private-user-images.githubusercontent.com/38065710/397601485-4b140504-ce66-42f6-9fd1-1430aa15a391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMTg5NTcsIm5iZiI6MTczNTExODY1NywicGF0aCI6Ii8zODA2NTcxMC8zOTc2MDE0ODUtNGIxNDA1MDQtY2U2Ni00MmY2LTlmZDEtMTQzMGFhMTVhMzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA5MjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MzAyNDdhODg0OGQxZWIwYTk4YmNhMTE5YjEwODkwOGY4M2Q0ZWE3ZGNjZDE4ZmRiZDBjMGE4YTNkMTZkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h-lt6iXr0guWmmoyk-CQXwrsGPkjf2o47wRUwHYXuxQ)
> 
> 具体的使用示例请查看 [examples](https://github.com/laugh12321/TensorRT-YOLO/tree/main/examples)

请问是否支持rensnet50训练的分类器？

**Comment by laugh12321** [comment]
@twd123-a 你试试可以正常导出不，可以导出就可以推理
