### ISSUE TITLE
[Help]: Upload Image Data to Device

### ISSUE THREAD

**Issue by paddy41601** [laugh12321/TensorRT-YOLO#80]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Does the API support uploading `deploy::Image` data to device memory before inference?  

For example, in the following code:  
```cpp
deploy::Image im(cvim.data, cvim.cols, cvim.rows);
deploy::DetResult result = model.predict(im);
```
Can the `im` data be uploaded to device memory before calling `model.predict`? If so, how can I achieve this?  

Thank you!

**Comment by laugh12321** [comment]
@paddy41601 我不太理解你的问题。

在 `predict` 函数内部，默认情况下（`cudaMem` 为 false 时）我们会自动将图像数据上传到设备内存。但如果你已经将图像数据提前上传到设备内存（例如，视频硬解码后的数据），并希望避免不必要的内存拷贝（即 `device -> host` 和 `host -> device` 之间的重复操作），可以在模型初始化时将 `cudaMem` 参数设置为 `true`。

如果在调用 `model.predict` 之前，图像数据已经上传到设备内存，则不需要在 `predict` 内部执行额外的内存上传操作。

以下是具体代码示例：

```cpp
std::string enginePath = "model.engine";
bool cudaMem = true;  // 设置为 true，表示图像数据已经在设备内存中
int deviceId = 0;  // 设备 ID
auto model = deploy::DeployDet(enginePath, cudaMem, deviceId);

...
deploy::Image im(device_image_ptr, width, height);  // 传入已在设备内存中的图像数据
auto result = model.predict(im);

**Comment by paddy41601** [comment]
I think this solve my problem. Thanks.

**Comment by laugh12321** [comment]
> I think this solve my problem. Thanks.

@paddy41601 No problem at all! I'm glad it helped. This issue will now be closed.
