### ISSUE TITLE
 [Question]: 支持NCNN吗

### ISSUE THREAD

**Issue by aaafdsf** [laugh12321/TensorRT-YOLO#9]
可以ncnn吗

**Comment by laugh12321** [comment]
你好，导出的EfficientNMS插件仅支持在TensorRT上使用。目前这个项目仅考虑做Nvidia设备的部署。

**Comment by aaafdsf** [comment]
raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>

**Comment by laugh12321** [comment]
在导出时模型会在git下拉对应的代码，可能是没有开代理的问题。
建议自行百度，可参考 https://blog.csdn.net/qq_43444008/article/details/100999809
